importScripts("shared.js");
(function(){
shadow$provide[11]=function(m,a,u,h){m=function(f){function b(n,p,r){Object.defineProperty(n,p,{value:r,enumerable:!0,configurable:!0,writable:!0});return n[p]}function d(n,p,r,E){p=Object.create((p&&p.prototype instanceof c?p:c).prototype);E=new x(E||[]);F(p,"_invoke",{value:t(n,r,E)});return p}function e(n,p,r){try{return{type:"normal",arg:n.call(p,r)}}catch(E){return{type:"throw",arg:E}}}function c(){}function g(){}function l(){}function v(n){["next","throw","return"].forEach(function(p){b(n,p,
function(r){return this._invoke(p,r)})})}function k(n,p){function r(y,K,L,Q){y=e(n[y],n,K);if("throw"===y.type)Q(y.arg);else{var S=y.arg;return(y=S.value)&&"object"===typeof y&&C.call(y,"__await")?p.resolve(y.__await).then(function(O){r("next",O,L,Q)},function(O){r("throw",O,L,Q)}):p.resolve(y).then(function(O){S.value=O;L(S)},function(O){return r("throw",O,L,Q)})}}var E;F(this,"_invoke",{value:function(y,K){function L(){return new p(function(Q,S){r(y,K,Q,S)})}return E=E?E.then(L,L):L()}})}function t(n,
p,r){var E=M;return function(y,K){if(E===U)throw Error("Generator is already running");if(E===R){if("throw"===y)throw K;return{value:G,done:!0}}r.method=y;for(r.arg=K;;){if(y=r.delegate)if(y=w(y,r)){if(y===N)continue;return y}if("next"===r.method)r.sent=r._sent=r.arg;else if("throw"===r.method){if(E===M)throw E=R,r.arg;r.dispatchException(r.arg)}else"return"===r.method&&r.abrupt("return",r.arg);E=U;y=e(n,p,r);if("normal"===y.type){E=r.done?R:P;if(y.arg===N)continue;return{value:y.arg,done:r.done}}"throw"===
y.type&&(E=R,r.method="throw",r.arg=y.arg)}}}function w(n,p){var r=p.method,E=n.iterator[r];if(E===G){p.delegate=null;if("throw"===r&&n.iterator["return"]&&(p.method="return",p.arg=G,w(n,p),"throw"===p.method))return N;"return"!==r&&(p.method="throw",p.arg=new TypeError("The iterator does not provide a '"+r+"' method"));return N}r=e(E,n.iterator,p.arg);if("throw"===r.type)return p.method="throw",p.arg=r.arg,p.delegate=null,N;r=r.arg;if(!r)return p.method="throw",p.arg=new TypeError("iterator result is not an object"),
p.delegate=null,N;if(r.done)p[n.resultName]=r.value,p.next=n.nextLoc,"return"!==p.method&&(p.method="next",p.arg=G);else return r;p.delegate=null;return N}function B(n){var p={tryLoc:n[0]};1 in n&&(p.catchLoc=n[1]);2 in n&&(p.finallyLoc=n[2],p.afterLoc=n[3]);this.tryEntries.push(p)}function D(n){var p=n.completion||{};p.type="normal";delete p.arg;n.completion=p}function x(n){this.tryEntries=[{tryLoc:"root"}];n.forEach(B,this);this.reset(!0)}function z(n){if(null!=n){var p=n[I];if(p)return p.call(n);
if("function"===typeof n.next)return n;if(!isNaN(n.length)){var r=-1;p=function y(){for(;++r<n.length;)if(C.call(n,r))return y.value=n[r],y.done=!1,y;y.value=G;y.done=!0;return y};return p.next=p}}throw new TypeError(typeof n+" is not iterable");}var A=Object.prototype,C=A.hasOwnProperty,F=Object.defineProperty||function(n,p,r){n[p]=r.value},G,q="function"===typeof Symbol?Symbol:{},I=q.iterator||"@@iterator",H=q.asyncIterator||"@@asyncIterator",J=q.toStringTag||"@@toStringTag";try{b({},"")}catch(n){b=
function(p,r,E){return p[r]=E}}f.wrap=d;var M="suspendedStart",P="suspendedYield",U="executing",R="completed",N={};q={};b(q,I,function(){return this});var T=Object.getPrototypeOf;(T=T&&T(T(z([]))))&&T!==A&&C.call(T,I)&&(q=T);var V=l.prototype=c.prototype=Object.create(q);g.prototype=l;F(V,"constructor",{value:l,configurable:!0});F(l,"constructor",{value:g,configurable:!0});g.displayName=b(l,J,"GeneratorFunction");f.isGeneratorFunction=function(n){return(n="function"===typeof n&&n.constructor)?n===
g||"GeneratorFunction"===(n.displayName||n.name):!1};f.mark=function(n){Object.setPrototypeOf?Object.setPrototypeOf(n,l):(n.__proto__=l,b(n,J,"GeneratorFunction"));n.prototype=Object.create(V);return n};f.awrap=function(n){return{__await:n}};v(k.prototype);b(k.prototype,H,function(){return this});f.AsyncIterator=k;f.async=function(n,p,r,E,y){void 0===y&&(y=Promise);var K=new k(d(n,p,r,E),y);return f.isGeneratorFunction(p)?K:K.next().then(function(L){return L.done?L.value:K.next()})};v(V);b(V,J,"Generator");
b(V,I,function(){return this});b(V,"toString",function(){return"[object Generator]"});f.keys=function(n){var p=Object(n),r=[],E;for(E in p)r.push(E);r.reverse();return function K(){for(;r.length;){var L=r.pop();if(L in p)return K.value=L,K.done=!1,K}K.done=!0;return K}};f.values=z;x.prototype={constructor:x,reset:function(n){this.next=this.prev=0;this.sent=this._sent=G;this.done=!1;this.delegate=null;this.method="next";this.arg=G;this.tryEntries.forEach(D);if(!n)for(var p in this)"t"===p.charAt(0)&&
C.call(this,p)&&!isNaN(+p.slice(1))&&(this[p]=G)},stop:function(){this.done=!0;var n=this.tryEntries[0].completion;if("throw"===n.type)throw n.arg;return this.rval},dispatchException:function(n){function p(S,O){K.type="throw";K.arg=n;r.next=S;O&&(r.method="next",r.arg=G);return!!O}if(this.done)throw n;for(var r=this,E=this.tryEntries.length-1;0<=E;--E){var y=this.tryEntries[E],K=y.completion;if("root"===y.tryLoc)return p("end");if(y.tryLoc<=this.prev){var L=C.call(y,"catchLoc"),Q=C.call(y,"finallyLoc");
if(L&&Q){if(this.prev<y.catchLoc)return p(y.catchLoc,!0);if(this.prev<y.finallyLoc)return p(y.finallyLoc)}else if(L){if(this.prev<y.catchLoc)return p(y.catchLoc,!0)}else if(Q){if(this.prev<y.finallyLoc)return p(y.finallyLoc)}else throw Error("try statement without catch or finally");}}},abrupt:function(n,p){for(var r=this.tryEntries.length-1;0<=r;--r){var E=this.tryEntries[r];if(E.tryLoc<=this.prev&&C.call(E,"finallyLoc")&&this.prev<E.finallyLoc){var y=E;break}}y&&("break"===n||"continue"===n)&&y.tryLoc<=
p&&p<=y.finallyLoc&&(y=null);r=y?y.completion:{};r.type=n;r.arg=p;return y?(this.method="next",this.next=y.finallyLoc,N):this.complete(r)},complete:function(n,p){if("throw"===n.type)throw n.arg;"break"===n.type||"continue"===n.type?this.next=n.arg:"return"===n.type?(this.rval=this.arg=n.arg,this.method="return",this.next="end"):"normal"===n.type&&p&&(this.next=p);return N},finish:function(n){for(var p=this.tryEntries.length-1;0<=p;--p){var r=this.tryEntries[p];if(r.finallyLoc===n)return this.complete(r.completion,
r.afterLoc),D(r),N}},"catch":function(n){for(var p=this.tryEntries.length-1;0<=p;--p){var r=this.tryEntries[p];if(r.tryLoc===n){n=r.completion;if("throw"===n.type){var E=n.arg;D(r)}return E}}throw Error("illegal catch attempt");},delegateYield:function(n,p,r){this.delegate={iterator:z(n),resultName:p,nextLoc:r};"next"===this.method&&(this.arg=G);return N}};return f}("object"===typeof u?u.exports:{});try{regeneratorRuntime=m}catch(f){"object"===typeof globalThis?globalThis.regeneratorRuntime=m:Function("r",
"regeneratorRuntime \x3d r")(m)}};
shadow$provide[12]=function(m,a,u,h){try{self["workbox:core:7.0.0"]&&_()}catch(f){}};
shadow$provide[13]=function(m,a,u,h){Object.defineProperties(h,{__esModule:{enumerable:!0,value:!0},logger:{enumerable:!0,get:function(){return null}}});a(12)};
shadow$provide[14]=function(m,a,u,h){Object.defineProperties(h,{__esModule:{enumerable:!0,value:!0},messages:{enumerable:!0,get:function(){return f}}});a(12);const f={"invalid-value":({paramName:b,validValueDescription:d,value:e})=>{if(!b||!d)throw Error("Unexpected input to 'invalid-value' error.");return`The '${b}' parameter was given a value with an `+`unexpected value. ${d} Received a value of `+`${JSON.stringify(e)}.`},"not-an-array":({moduleName:b,className:d,funcName:e,paramName:c})=>{if(!(b&&
d&&e&&c))throw Error("Unexpected input to 'not-an-array' error.");return`The parameter '${c}' passed into `+`'${b}.${d}.${e}()' must be an array.`},"incorrect-type":({expectedType:b,paramName:d,moduleName:e,className:c,funcName:g})=>{if(!(b&&d&&e&&g))throw Error("Unexpected input to 'incorrect-type' error.");return`The parameter '${d}' passed into `+`'${e}.${c?`${c}.`:""}`+`${g}()' must be of type ${b}.`},"incorrect-class":({expectedClassName:b,paramName:d,moduleName:e,className:c,funcName:g,isReturnValueProblem:l})=>
{if(!b||!e||!g)throw Error("Unexpected input to 'incorrect-class' error.");c=c?`${c}.`:"";return l?"The return value from "+`'${e}.${c}${g}()' `+`must be an instance of class ${b}.`:`The parameter '${d}' passed into `+`'${e}.${c}${g}()' `+`must be an instance of class ${b}.`},"missing-a-method":({expectedMethod:b,paramName:d,moduleName:e,className:c,funcName:g})=>{if(!(b&&d&&e&&c&&g))throw Error("Unexpected input to 'missing-a-method' error.");return`${e}.${c}.${g}() expected the `+`'${d}' parameter to expose a '${b}' method.`},
"add-to-cache-list-unexpected-type":({entry:b})=>"An unexpected entry was passed to 'workbox-precaching.PrecacheController.addToCacheList()' The entry "+`'${JSON.stringify(b)}' isn't supported. You must supply an array of `+"strings with one or more characters, objects with a url property or Request objects.","add-to-cache-list-conflicting-entries":({firstEntry:b,secondEntry:d})=>{if(!b||!d)throw Error("Unexpected input to 'add-to-cache-list-duplicate-entries' error.");return"Two of the entries passed to 'workbox-precaching.PrecacheController.addToCacheList()' had the URL "+
`${b} but different revision details. Workbox is `+"unable to cache and version the asset correctly. Please remove one of the entries."},"plugin-error-request-will-fetch":({thrownErrorMessage:b})=>{if(!b)throw Error("Unexpected input to 'plugin-error-request-will-fetch', error.");return"An error was thrown by a plugins 'requestWillFetch()' method. "+`The thrown error message was: '${b}'.`},"invalid-cache-name":({cacheNameId:b,value:d})=>{if(!b)throw Error("Expected a 'cacheNameId' for error 'invalid-cache-name'");
return"You must provide a name containing at least one character for "+`setCacheDetails({${b}: '...'}). Received a value of `+`'${JSON.stringify(d)}'`},"unregister-route-but-not-found-with-method":({method:b})=>{if(!b)throw Error("Unexpected input to 'unregister-route-but-not-found-with-method' error.");return"The route you're trying to unregister was not  previously "+`registered for the method type '${b}'.`},"unregister-route-route-not-registered":()=>"The route you're trying to unregister was not previously registered.",
"queue-replay-failed":({name:b})=>`Replaying the background sync queue '${b}' failed.`,"duplicate-queue-name":({name:b})=>`The Queue name '${b}' is already being used. `+"All instances of backgroundSync.Queue must be given unique names.","expired-test-without-max-age":({methodName:b,paramName:d})=>`The '${b}()' method can only be used when the `+`'${d}' is used in the constructor.`,"unsupported-route-type":({moduleName:b,className:d,funcName:e,paramName:c})=>`The supplied '${c}' parameter was an unsupported type. `+
`Please check the docs for ${b}.${d}.${e} for `+"valid input types.","not-array-of-class":({value:b,expectedClass:d,moduleName:e,className:c,funcName:g,paramName:l})=>`The supplied '${l}' parameter must be an array of `+`'${d}' objects. Received '${JSON.stringify(b)},'. `+`Please check the call to ${e}.${c}.${g}() `+"to fix the issue.","max-entries-or-age-required":({moduleName:b,className:d,funcName:e})=>"You must define either config.maxEntries or config.maxAgeSeconds"+`in ${b}.${d}.${e}`,"statuses-or-headers-required":({moduleName:b,
className:d,funcName:e})=>"You must define either config.statuses or config.headers"+`in ${b}.${d}.${e}`,"invalid-string":({moduleName:b,funcName:d,paramName:e})=>{if(!e||!b||!d)throw Error("Unexpected input to 'invalid-string' error.");return`When using strings, the '${e}' parameter must start with `+"'http' (for cross-origin matches) or '/' (for same-origin matches). "+`Please see the docs for ${b}.${d}() for `+"more info."},"channel-name-required":()=>"You must provide a channelName to construct a BroadcastCacheUpdate instance.",
"invalid-responses-are-same-args":()=>"The arguments passed into responsesAreSame() appear to be invalid. Please ensure valid Responses are used.","expire-custom-caches-only":()=>"You must provide a 'cacheName' property when using the expiration plugin with a runtime caching strategy.","unit-must-be-bytes":({normalizedRangeHeader:b})=>{if(!b)throw Error("Unexpected input to 'unit-must-be-bytes' error.");return"The 'unit' portion of the Range header must be set to 'bytes'. "+`The Range header provided was "${b}"`},
"single-range-only":({normalizedRangeHeader:b})=>{if(!b)throw Error("Unexpected input to 'single-range-only' error.");return"Multiple ranges are not supported. Please use a  single start value, and optional end value. The Range header provided was "+`"${b}"`},"invalid-range-values":({normalizedRangeHeader:b})=>{if(!b)throw Error("Unexpected input to 'invalid-range-values' error.");return"The Range header is missing both start and end values. At least one of those values is needed. The Range header provided was "+
`"${b}"`},"no-range-header":()=>"No Range header was found in the Request provided.","range-not-satisfiable":({size:b,start:d,end:e})=>`The start (${d}) and end (${e}) values in the Range are `+`not satisfiable by the cached response, which is ${b} bytes.`,"attempt-to-cache-non-get-request":({url:b,method:d})=>`Unable to cache '${b}' because it is a '${d}' request and `+"only 'GET' requests can be cached.","cache-put-with-no-response":({url:b})=>`There was an attempt to cache '${b}' but the response was not `+
"defined.","no-response":({url:b,error:d})=>{b=`The strategy could not generate a response for '${b}'.`;d&&(b+=` The underlying error is ${d}.`);return b},"bad-precaching-response":({url:b,status:d})=>`The precaching request for '${b}' failed`+(d?` with an HTTP status of ${d}.`:"."),"non-precached-url":({url:b})=>`createHandlerBoundToURL('${b}') was called, but that URL is `+"not precached. Please pass in a URL that is precached instead.","add-to-cache-list-conflicting-integrities":({url:b})=>"Two of the entries passed to 'workbox-precaching.PrecacheController.addToCacheList()' had the URL "+
`${b} with different integrity values. Please remove one of them.`,"missing-precache-entry":({cacheName:b,url:d})=>`Unable to find a precached response in ${b} for ${d}.`,"cross-origin-copy-response":({origin:b})=>"workbox-core.copyResponse() can only be used with same-origin "+`responses. It was passed a response with origin ${b}.`,"opaque-streams-source":({type:b})=>{const d="One of the workbox-streams sources resulted in an "+`'${b}' response.`;return"opaqueredirect"===b?`${d} Please do not use a navigation request that results `+
"in a redirect as a source.":`${d} Please ensure your sources are CORS-enabled.`}}};
shadow$provide[15]=function(m,a,u,h){Object.defineProperties(h,{__esModule:{enumerable:!0,value:!0},messageGenerator:{enumerable:!0,get:function(){return f}}});a(14);a(12);const f=(b,...d)=>{0<d.length&&(b+=` :: ${JSON.stringify(d)}`);return b}};
shadow$provide[16]=function(m,a,u,h){Object.defineProperties(h,{__esModule:{enumerable:!0,value:!0},WorkboxError:{enumerable:!0,get:function(){return b}}});var f=a(15);a(12);class b extends Error{constructor(d,e){super((0,f.messageGenerator)(d,e));this.name=d;this.details=e}}};
shadow$provide[17]=function(m,a,u,h){Object.defineProperties(h,{__esModule:{enumerable:!0,value:!0},assert:{enumerable:!0,get:function(){return null}}});a(16);a(12)};
shadow$provide[18]=function(m,a,u,h){Object.defineProperties(h,{__esModule:{enumerable:!0,value:!0},quotaErrorCallbacks:{enumerable:!0,get:function(){return f}}});a(12);const f=new Set};
shadow$provide[19]=function(m,a,u,h){function f(d){b.quotaErrorCallbacks.add(d)}Object.defineProperties(h,{__esModule:{enumerable:!0,value:!0},registerQuotaErrorCallback:{enumerable:!0,get:function(){return f}}});a(13);a(17);var b=a(18);a(12)};
shadow$provide[20]=function(m,a,u,h){Object.defineProperties(h,{__esModule:{enumerable:!0,value:!0},cacheNames:{enumerable:!0,get:function(){return e}}});a(12);const f={googleAnalytics:"googleAnalytics",precache:"precache-v2",prefix:"workbox",runtime:"runtime",suffix:"undefined"!==typeof registration?registration.scope:""},b=c=>[f.prefix,c,f.suffix].filter(g=>g&&0<g.length).join("-"),d=c=>{for(const g of Object.keys(f))c(g)},e={updateDetails:c=>{d(g=>{"string"===typeof c[g]&&(f[g]=c[g])})},getGoogleAnalyticsName:c=>
c||b(f.googleAnalytics),getPrecacheName:c=>c||b(f.precache),getPrefix:()=>f.prefix,getRuntimeName:c=>c||b(f.runtime),getSuffix:()=>f.suffix}};
shadow$provide[21]=function(m,a,u,h){function f(d,e){d=new URL(d);for(const c of e)d.searchParams.delete(c);return d.href}async function b(d,e,c,g){const l=f(e.url,c);if(e.url===l)return d.match(e,g);const v=Object.assign(Object.assign({},g),{ignoreSearch:!0});e=await d.keys(e,v);for(const k of e)if(e=f(k.url,c),l===e)return d.match(k,g)}Object.defineProperties(h,{__esModule:{enumerable:!0,value:!0},cacheMatchIgnoreParams:{enumerable:!0,get:function(){return b}}});a(12)};
shadow$provide[22]=function(m,a,u,h){function f(){if(void 0===b)try{new ReadableStream({start(){}}),b=!0}catch(d){b=!1}return b}Object.defineProperties(h,{__esModule:{enumerable:!0,value:!0},canConstructReadableStream:{enumerable:!0,get:function(){return f}}});a(12);let b};
shadow$provide[23]=function(m,a,u,h){function f(){if(void 0===b){const d=new Response("");if("body"in d)try{new Response(d.body),b=!0}catch(e){b=!1}b=!1}return b}Object.defineProperties(h,{__esModule:{enumerable:!0,value:!0},canConstructResponseFromBodyStream:{enumerable:!0,get:function(){return f}}});a(12);let b};
shadow$provide[24]=function(m,a,u,h){function f(b){void b.then(()=>{})}Object.defineProperties(h,{__esModule:{enumerable:!0,value:!0},dontWaitFor:{enumerable:!0,get:function(){return f}}});a(12)};
shadow$provide[25]=function(m,a,u,h){Object.defineProperties(h,{__esModule:{enumerable:!0,value:!0},Deferred:{enumerable:!0,get:function(){return f}}});a(12);class f{constructor(){this.promise=new Promise((b,d)=>{this.resolve=b;this.reject=d})}}};
shadow$provide[26]=function(m,a,u,h){async function f(){for(const d of b.quotaErrorCallbacks)await d()}Object.defineProperties(h,{__esModule:{enumerable:!0,value:!0},executeQuotaErrorCallbacks:{enumerable:!0,get:function(){return f}}});a(13);var b=a(18);a(12)};
shadow$provide[27]=function(m,a,u,h){Object.defineProperties(h,{__esModule:{enumerable:!0,value:!0},getFriendlyURL:{enumerable:!0,get:function(){return f}}});a(12);const f=b=>(new URL(String(b),location.href)).href.replace(new RegExp(`^${location.origin}`),"")};
shadow$provide[28]=function(m,a,u,h){function f(b){return new Promise(d=>setTimeout(d,b))}Object.defineProperties(h,{__esModule:{enumerable:!0,value:!0},timeout:{enumerable:!0,get:function(){return f}}});a(12)};
shadow$provide[29]=function(m,a,u,h){async function f(d){if(d){for(var e=await self.clients.matchAll({type:"window"}),c=new Set(e.map(v=>v.id)),g,l=performance.now();2E3>performance.now()-l;){e=await self.clients.matchAll({type:"window"});if(g=e.find(v=>d?v.id===d:!c.has(v.id)))break;await (0,b.timeout)(100)}return g}}Object.defineProperties(h,{__esModule:{enumerable:!0,value:!0},resultingClientExists:{enumerable:!0,get:function(){return f}}});var b=a(28);a(12)};
shadow$provide[30]=function(m,a,u,h){function f(b,d){d=d();b.waitUntil(d);return d}Object.defineProperties(h,{__esModule:{enumerable:!0,value:!0},waitUntil:{enumerable:!0,get:function(){return f}}});a(12)};
shadow$provide[31]=function(m,a,u,h){Object.defineProperties(h,{__esModule:{enumerable:!0,value:!0},Deferred:{enumerable:!0,get:function(){return l.Deferred}},WorkboxError:{enumerable:!0,get:function(){return x.WorkboxError}},assert:{enumerable:!0,get:function(){return f.assert}},cacheMatchIgnoreParams:{enumerable:!0,get:function(){return d.cacheMatchIgnoreParams}},cacheNames:{enumerable:!0,get:function(){return b.cacheNames}},canConstructReadableStream:{enumerable:!0,get:function(){return e.canConstructReadableStream}},
canConstructResponseFromBodyStream:{enumerable:!0,get:function(){return c.canConstructResponseFromBodyStream}},dontWaitFor:{enumerable:!0,get:function(){return g.dontWaitFor}},executeQuotaErrorCallbacks:{enumerable:!0,get:function(){return v.executeQuotaErrorCallbacks}},getFriendlyURL:{enumerable:!0,get:function(){return k.getFriendlyURL}},logger:{enumerable:!0,get:function(){return t.logger}},resultingClientExists:{enumerable:!0,get:function(){return w.resultingClientExists}},timeout:{enumerable:!0,
get:function(){return B.timeout}},waitUntil:{enumerable:!0,get:function(){return D.waitUntil}}});var f=a(17),b=a(20),d=a(21),e=a(22),c=a(23),g=a(24),l=a(25),v=a(26),k=a(27),t=a(13),w=a(29),B=a(28),D=a(30),x=a(16);a(12)};
shadow$provide[32]=function(m,a,u,h){Object.defineProperties(h,{__esModule:{enumerable:!0,value:!0},cacheNames:{enumerable:!0,get:function(){return b}}});var f=a(20);a(12);const b={get googleAnalytics(){return f.cacheNames.getGoogleAnalyticsName()},get precache(){return f.cacheNames.getPrecacheName()},get prefix(){return f.cacheNames.getPrefix()},get runtime(){return f.cacheNames.getRuntimeName()},get suffix(){return f.cacheNames.getSuffix()}}};
shadow$provide[33]=function(m,a,u,h){async function f(e,c){var g=null;e.url&&(g=(new URL(e.url)).origin);if(g!==self.location.origin)throw new d.WorkboxError("cross-origin-copy-response",{origin:g});e=e.clone();g={headers:new Headers(e.headers),status:e.status,statusText:e.statusText};c=c?c(g):g;e=(0,b.canConstructResponseFromBodyStream)()?e.body:await e.blob();return new Response(e,c)}Object.defineProperties(h,{__esModule:{enumerable:!0,value:!0},copyResponse:{enumerable:!0,get:function(){return f}}});
var b=a(23),d=a(16);a(12)};
shadow$provide[34]=function(m,a,u,h){function f(){self.addEventListener("activate",()=>self.clients.claim())}Object.defineProperties(h,{__esModule:{enumerable:!0,value:!0},clientsClaim:{enumerable:!0,get:function(){return f}}});a(12)};
shadow$provide[35]=function(m,a,u,h){function f(d){b.cacheNames.updateDetails(d)}Object.defineProperties(h,{__esModule:{enumerable:!0,value:!0},setCacheNameDetails:{enumerable:!0,get:function(){return f}}});a(17);var b=a(20);a(16);a(12)};
shadow$provide[36]=function(m,a,u,h){function f(){void self.skipWaiting()}Object.defineProperties(h,{__esModule:{enumerable:!0,value:!0},skipWaiting:{enumerable:!0,get:function(){return f}}});a(13);a(12)};
shadow$provide[37]=function(m,a,u,h){a(12)};
shadow$provide[38]=function(m,a,u,h){Object.defineProperties(h,{__esModule:{enumerable:!0,value:!0},_private:{enumerable:!0,get:function(){return b}},cacheNames:{enumerable:!0,get:function(){return d.cacheNames}},clientsClaim:{enumerable:!0,get:function(){return c.clientsClaim}},copyResponse:{enumerable:!0,get:function(){return e.copyResponse}},registerQuotaErrorCallback:{enumerable:!0,get:function(){return f.registerQuotaErrorCallback}},setCacheNameDetails:{enumerable:!0,get:function(){return g.setCacheNameDetails}},
skipWaiting:{enumerable:!0,get:function(){return l.skipWaiting}}});var f=a(19),b=a(31),d=a(32),e=a(33),c=a(34),g=a(35),l=a(36);a(12);m=a(37);a.exportCopy(u,m)};
shadow$provide[39]=function(m,a,u,h){try{self["workbox:routing:7.0.0"]&&_()}catch(f){}};
shadow$provide[40]=function(m,a,u,h){Object.defineProperties(h,{__esModule:{enumerable:!0,value:!0},defaultMethod:{enumerable:!0,get:function(){return"GET"}},validMethods:{enumerable:!0,get:function(){return f}}});a(39);const f="DELETE GET HEAD PATCH POST PUT".split(" ")};
shadow$provide[41]=function(m,a,u,h){Object.defineProperties(h,{__esModule:{enumerable:!0,value:!0},normalizeHandler:{enumerable:!0,get:function(){return f}}});a(17);a(39);const f=b=>b&&"object"===typeof b?b:{handle:b}};
shadow$provide[42]=function(m,a,u,h){Object.defineProperties(h,{__esModule:{enumerable:!0,value:!0},Route:{enumerable:!0,get:function(){return d}}});a(17);var f=a(40),b=a(41);a(39);class d{constructor(e,c,g=f.defaultMethod){this.handler=(0,b.normalizeHandler)(c);this.match=e;this.method=g}setCatchHandler(e){this.catchHandler=(0,b.normalizeHandler)(e)}}};
shadow$provide[43]=function(m,a,u,h){Object.defineProperties(h,{__esModule:{enumerable:!0,value:!0},NavigationRoute:{enumerable:!0,get:function(){return f}}});a(17);a(13);m=a(42);a(39);class f extends m.Route{constructor(b,{allowlist:d=[/./],denylist:e=[]}={}){super(c=>this._match(c),b);this._allowlist=d;this._denylist=e}_match({url:b,request:d}){if(d&&"navigate"!==d.mode)return!1;const e=b.pathname+b.search;for(const c of this._denylist)if(c.test(e))return!1;return this._allowlist.some(c=>c.test(e))?
!0:!1}}};
shadow$provide[44]=function(m,a,u,h){Object.defineProperties(h,{__esModule:{enumerable:!0,value:!0},RegExpRoute:{enumerable:!0,get:function(){return f}}});a(17);a(13);m=a(42);a(39);class f extends m.Route{constructor(b,d,e){super(({url:c})=>{const g=b.exec(c.href);if(g&&(c.origin===location.origin||0===g.index))return g.slice(1)},d,e)}}};
shadow$provide[45]=function(m,a,u,h){Object.defineProperties(h,{__esModule:{enumerable:!0,value:!0},Router:{enumerable:!0,get:function(){return e}}});a(17);a(27);var f=a(40);a(13);var b=a(41),d=a(16);a(39);class e{constructor(){this._routes=new Map;this._defaultHandlerMap=new Map}get routes(){return this._routes}addFetchListener(){self.addEventListener("fetch",c=>{var {request:g}=c;(g=this.handleRequest({request:g,event:c}))&&c.respondWith(g)})}addCacheListener(){self.addEventListener("message",c=>
{if(c.data&&"CACHE_URLS"===c.data.type){var {payload:g}=c.data;g=Promise.all(g.urlsToCache.map(l=>{"string"===typeof l&&(l=[l]);l=new Request(...l);return this.handleRequest({request:l,event:c})}));c.waitUntil(g);c.ports&&c.ports[0]&&void g.then(()=>c.ports[0].postMessage(!0))}})}handleRequest({request:c,event:g}){const l=new URL(c.url,location.href);if(l.protocol.startsWith("http")){var {params:v,route:k}=this.findMatchingRoute({event:g,request:c,sameOrigin:l.origin===location.origin,url:l}),t=k&&
k.handler,w=c.method;!t&&this._defaultHandlerMap.has(w)&&(t=this._defaultHandlerMap.get(w));if(t){try{var B=t.handle({url:l,request:c,event:g,params:v})}catch(x){B=Promise.reject(x)}var D=k&&k.catchHandler;B instanceof Promise&&(this._catchHandler||D)&&(B=B.catch(async x=>{if(D)try{return await D.handle({url:l,request:c,event:g,params:v})}catch(z){z instanceof Error&&(x=z)}if(this._catchHandler)return this._catchHandler.handle({url:l,request:c,event:g});throw x;}));return B}}}findMatchingRoute({url:c,
sameOrigin:g,request:l,event:v}){var k=this._routes.get(l.method)||[];for(const t of k)if(k=t.match({url:c,sameOrigin:g,request:l,event:v}))return c=k,Array.isArray(c)&&0===c.length?c=void 0:k.constructor===Object&&0===Object.keys(k).length?c=void 0:"boolean"===typeof k&&(c=void 0),{route:t,params:c};return{}}setDefaultHandler(c,g=f.defaultMethod){this._defaultHandlerMap.set(g,(0,b.normalizeHandler)(c))}setCatchHandler(c){this._catchHandler=(0,b.normalizeHandler)(c)}registerRoute(c){this._routes.has(c.method)||
this._routes.set(c.method,[]);this._routes.get(c.method).push(c)}unregisterRoute(c){if(!this._routes.has(c.method))throw new d.WorkboxError("unregister-route-but-not-found-with-method",{method:c.method});const g=this._routes.get(c.method).indexOf(c);if(-1<g)this._routes.get(c.method).splice(g,1);else throw new d.WorkboxError("unregister-route-route-not-registered");}}};
shadow$provide[46]=function(m,a,u,h){Object.defineProperties(h,{__esModule:{enumerable:!0,value:!0},getOrCreateDefaultRouter:{enumerable:!0,get:function(){return d}}});var f=a(45);a(39);let b;const d=()=>{b||(b=new f.Router,b.addFetchListener(),b.addCacheListener());return b}};
shadow$provide[47]=function(m,a,u,h){function f(g,l,v){if("string"===typeof g){const k=new URL(g,location.href);g=new d.Route(({url:t})=>t.href===k.href,l,v)}else if(g instanceof RegExp)g=new e.RegExpRoute(g,l,v);else if("function"===typeof g)g=new d.Route(g,l,v);else if(!(g instanceof d.Route))throw new b.WorkboxError("unsupported-route-type",{moduleName:"workbox-routing",funcName:"registerRoute",paramName:"capture"});(0,c.getOrCreateDefaultRouter)().registerRoute(g);return g}Object.defineProperties(h,
{__esModule:{enumerable:!0,value:!0},registerRoute:{enumerable:!0,get:function(){return f}}});a(13);var b=a(16),d=a(42),e=a(44),c=a(46);a(39)};
shadow$provide[48]=function(m,a,u,h){function f(d){(0,b.getOrCreateDefaultRouter)().setCatchHandler(d)}Object.defineProperties(h,{__esModule:{enumerable:!0,value:!0},setCatchHandler:{enumerable:!0,get:function(){return f}}});var b=a(46);a(39)};
shadow$provide[49]=function(m,a,u,h){function f(d){(0,b.getOrCreateDefaultRouter)().setDefaultHandler(d)}Object.defineProperties(h,{__esModule:{enumerable:!0,value:!0},setDefaultHandler:{enumerable:!0,get:function(){return f}}});var b=a(46);a(39)};
shadow$provide[50]=function(m,a,u,h){Object.defineProperties(h,{__esModule:{enumerable:!0,value:!0},NavigationRoute:{enumerable:!0,get:function(){return f.NavigationRoute}},RegExpRoute:{enumerable:!0,get:function(){return b.RegExpRoute}},Route:{enumerable:!0,get:function(){return e.Route}},Router:{enumerable:!0,get:function(){return c.Router}},registerRoute:{enumerable:!0,get:function(){return d.registerRoute}},setCatchHandler:{enumerable:!0,get:function(){return g.setCatchHandler}},setDefaultHandler:{enumerable:!0,
get:function(){return l.setDefaultHandler}}});var f=a(43),b=a(44),d=a(47),e=a(42),c=a(45),g=a(48),l=a(49);a(39)};
shadow$provide[51]=function(m,a,u,h){try{self["workbox:precaching:7.0.0"]&&_()}catch(f){}};
shadow$provide[52]=function(m,a,u,h){function f(d){if(!d)throw new b.WorkboxError("add-to-cache-list-unexpected-type",{entry:d});if("string"===typeof d)return d=new URL(d,location.href),{cacheKey:d.href,url:d.href};const {revision:e,url:c}=d;if(!c)throw new b.WorkboxError("add-to-cache-list-unexpected-type",{entry:d});if(!e)return d=new URL(c,location.href),{cacheKey:d.href,url:d.href};d=new URL(c,location.href);const g=new URL(c,location.href);d.searchParams.set("__WB_REVISION__",e);return{cacheKey:d.href,
url:g.href}}Object.defineProperties(h,{__esModule:{enumerable:!0,value:!0},createCacheKey:{enumerable:!0,get:function(){return f}}});var b=a(16);a(51)};
shadow$provide[53]=function(m,a,u,h){Object.defineProperties(h,{__esModule:{enumerable:!0,value:!0},PrecacheInstallReportPlugin:{enumerable:!0,get:function(){return f}}});a(51);class f{constructor(){this.updatedURLs=[];this.notUpdatedURLs=[];this.handlerWillStart=async({request:b,state:d})=>{d&&(d.originalRequest=b)};this.cachedResponseWillBeUsed=async({event:b,state:d,cachedResponse:e})=>{"install"===b.type&&d&&d.originalRequest&&d.originalRequest instanceof Request&&(b=d.originalRequest.url,e?this.notUpdatedURLs.push(b):
this.updatedURLs.push(b));return e}}}};
shadow$provide[54]=function(m,a,u,h){Object.defineProperties(h,{__esModule:{enumerable:!0,value:!0},PrecacheCacheKeyPlugin:{enumerable:!0,get:function(){return f}}});a(51);class f{constructor({precacheController:b}){this.cacheKeyWillBeUsed=async({request:d,params:e})=>(e=(null===e||void 0===e?void 0:e.cacheKey)||this._precacheController.getCacheKeyForURL(d.url))?new Request(e,{headers:d.headers}):d;this._precacheController=b}}};
shadow$provide[55]=function(m,a,u,h){function f(d){const e=d.length;if(0<e){b.logger.groupCollapsed("During precaching cleanup, "+`${e} cached `+`request${1===e?" was":"s were"} deleted.`);b.logger.groupCollapsed("Deleted Cache Requests");for(const c of d)b.logger.log(c);b.logger.groupEnd();b.logger.groupEnd()}}Object.defineProperties(h,{__esModule:{enumerable:!0,value:!0},printCleanupDetails:{enumerable:!0,get:function(){return f}}});var b=a(13);a(51)};
shadow$provide[56]=function(m,a,u,h){function f(e,c){if(0!==c.length){d.logger.groupCollapsed(e);for(const g of c)d.logger.log(g);d.logger.groupEnd()}}function b(e,c){var g=e.length;const l=c.length;if(g||l)g=`Precaching ${g} file${1===g?"":"s"}.`,0<l&&(g+=` ${l} `+`file${1===l?" is":"s are"} already cached.`),d.logger.groupCollapsed(g),f("View newly precached URLs.",e),f("View previously precached URLs.",c),d.logger.groupEnd()}Object.defineProperties(h,{__esModule:{enumerable:!0,value:!0},printInstallDetails:{enumerable:!0,
get:function(){return b}}});var d=a(13);a(51)};
shadow$provide[57]=function(m,a,u,h){try{self["workbox:strategies:7.0.0"]&&_()}catch(f){}};
shadow$provide[58]=function(m,a,u,h){function f(k){return"string"===typeof k?new Request(k):k}Object.defineProperties(h,{__esModule:{enumerable:!0,value:!0},StrategyHandler:{enumerable:!0,get:function(){return v}}});a(17);var b=a(21),d=a(25),e=a(26),c=a(27);a(13);var g=a(28),l=a(16);a(57);class v{constructor(k,t){this._cacheKeys={};Object.assign(this,t);this.event=t.event;this._strategy=k;this._handlerDeferred=new d.Deferred;this._extendLifetimePromises=[];this._plugins=[...k.plugins];this._pluginStateMap=
new Map;for(const w of this._plugins)this._pluginStateMap.set(w,{});this.event.waitUntil(this._handlerDeferred.promise)}async fetch(k){const {event:t}=this;k=f(k);if("navigate"===k.mode&&t instanceof FetchEvent&&t.preloadResponse){var w=await t.preloadResponse;if(w)return w}w=this.hasCallback("fetchDidFail")?k.clone():null;try{for(var B of this.iterateCallbacks("requestWillFetch"))k=await B({request:k.clone(),event:t})}catch(D){if(D instanceof Error)throw new l.WorkboxError("plugin-error-request-will-fetch",
{thrownErrorMessage:D.message});}B=k.clone();try{let D;D=await fetch(k,"navigate"===k.mode?void 0:this._strategy.fetchOptions);for(const x of this.iterateCallbacks("fetchDidSucceed"))D=await x({event:t,request:B,response:D});return D}catch(D){throw w&&await this.runCallbacks("fetchDidFail",{error:D,event:t,originalRequest:w.clone(),request:B.clone()}),D;}}async fetchAndCachePut(k){const t=await this.fetch(k),w=t.clone();void this.waitUntil(this.cachePut(k,w));return t}async cacheMatch(k){k=f(k);const {cacheName:t,
matchOptions:w}=this._strategy;k=await this.getCacheKey(k,"read");var B=Object.assign(Object.assign({},w),{cacheName:t});B=await caches.match(k,B);for(const D of this.iterateCallbacks("cachedResponseWillBeUsed"))B=await D({cacheName:t,matchOptions:w,cachedResponse:B,request:k,event:this.event})||void 0;return B}async cachePut(k,t){k=f(k);await (0,g.timeout)(0);k=await this.getCacheKey(k,"write");if(!t)throw new l.WorkboxError("cache-put-with-no-response",{url:(0,c.getFriendlyURL)(k.url)});t=await this._ensureResponseSafeToCache(t);
if(!t)return!1;const {cacheName:w,matchOptions:B}=this._strategy,D=await self.caches.open(w),x=this.hasCallback("cacheDidUpdate"),z=x?await (0,b.cacheMatchIgnoreParams)(D,k.clone(),["__WB_REVISION__"],B):null;try{await D.put(k,x?t.clone():t)}catch(A){if(A instanceof Error)throw"QuotaExceededError"===A.name&&await (0,e.executeQuotaErrorCallbacks)(),A;}for(const A of this.iterateCallbacks("cacheDidUpdate"))await A({cacheName:w,oldResponse:z,newResponse:t.clone(),request:k,event:this.event});return!0}async getCacheKey(k,
t){const w=`${k.url} | ${t}`;if(!this._cacheKeys[w]){for(const B of this.iterateCallbacks("cacheKeyWillBeUsed"))k=f(await B({mode:t,request:k,event:this.event,params:this.params}));this._cacheKeys[w]=k}return this._cacheKeys[w]}hasCallback(k){for(const t of this._strategy.plugins)if(k in t)return!0;return!1}async runCallbacks(k,t){for(const w of this.iterateCallbacks(k))await w(t)}*iterateCallbacks(k){for(const t of this._strategy.plugins)if("function"===typeof t[k]){const w=this._pluginStateMap.get(t);
yield(B=>{B=Object.assign(Object.assign({},B),{state:w});return t[k](B)})}}waitUntil(k){this._extendLifetimePromises.push(k);return k}async doneWaiting(){let k;for(;k=this._extendLifetimePromises.shift();)await k}destroy(){this._handlerDeferred.resolve(null)}async _ensureResponseSafeToCache(k){let t=!1;for(const w of this.iterateCallbacks("cacheWillUpdate"))if(k=await w({request:this.request,response:k,event:this.event})||void 0,t=!0,!k)break;t||k&&200!==k.status&&(k=void 0);return k}}};
shadow$provide[59]=function(m,a,u,h){Object.defineProperties(h,{__esModule:{enumerable:!0,value:!0},Strategy:{enumerable:!0,get:function(){return e}}});var f=a(20),b=a(16);a(13);a(27);var d=a(58);a(57);class e{constructor(c={}){this.cacheName=f.cacheNames.getRuntimeName(c.cacheName);this.plugins=c.plugins||[];this.fetchOptions=c.fetchOptions;this.matchOptions=c.matchOptions}handle(c){[c]=this.handleAll(c);return c}handleAll(c){c instanceof FetchEvent&&(c={event:c,request:c.request});var g=c.event;
const l="string"===typeof c.request?new Request(c.request):c.request,v=new d.StrategyHandler(this,{event:g,request:l,params:"params"in c?c.params:void 0});c=this._getResponse(v,l,g);g=this._awaitComplete(c,v,l,g);return[c,g]}async _getResponse(c,g,l){await c.runCallbacks("handlerWillStart",{event:l,request:g});let v=void 0;try{if(v=await this._handle(g,c),!v||"error"===v.type)throw new b.WorkboxError("no-response",{url:g.url});}catch(k){if(k instanceof Error)for(const t of c.iterateCallbacks("handlerDidError"))if(v=
await t({error:k,event:l,request:g}))break;if(!v)throw k;}for(const k of c.iterateCallbacks("handlerWillRespond"))v=await k({event:l,request:g,response:v});return v}async _awaitComplete(c,g,l,v){let k,t;try{k=await c}catch(w){}try{await g.runCallbacks("handlerDidRespond",{event:v,request:l,response:k}),await g.doneWaiting()}catch(w){w instanceof Error&&(t=w)}await g.runCallbacks("handlerDidComplete",{event:v,request:l,response:k,error:t});g.destroy();if(t)throw t;}}};
shadow$provide[60]=function(m,a,u,h){Object.defineProperties(h,{__esModule:{enumerable:!0,value:!0},PrecacheStrategy:{enumerable:!0,get:function(){return e}}});var f=a(33),b=a(20);a(27);a(13);var d=a(16);m=a(59);a(51);class e extends m.Strategy{constructor(c={}){c.cacheName=b.cacheNames.getPrecacheName(c.cacheName);super(c);this._fallbackToNetwork=!1===c.fallbackToNetwork?!1:!0;this.plugins.push(e.copyRedirectedCacheableResponsesPlugin)}async _handle(c,g){const l=await g.cacheMatch(c);return l?l:
g.event&&"install"===g.event.type?await this._handleInstall(c,g):await this._handleFetch(c,g)}async _handleFetch(c,g){var l=g.params||{};if(this._fallbackToNetwork){l=l.integrity;var v=c.integrity;const k=!v||v===l;v=await g.fetch(new Request(c,{integrity:"no-cors"!==c.mode?v||l:void 0}));l&&k&&"no-cors"!==c.mode&&(this._useDefaultCacheabilityPluginIfNeeded(),await g.cachePut(c,v.clone()))}else throw new d.WorkboxError("missing-precache-entry",{cacheName:this.cacheName,url:c.url});return v}async _handleInstall(c,
g){this._useDefaultCacheabilityPluginIfNeeded();const l=await g.fetch(c);if(!await g.cachePut(c,l.clone()))throw new d.WorkboxError("bad-precaching-response",{url:c.url,status:l.status});return l}_useDefaultCacheabilityPluginIfNeeded(){let c=null,g=0;for(const [l,v]of this.plugins.entries())v!==e.copyRedirectedCacheableResponsesPlugin&&(v===e.defaultPrecacheCacheabilityPlugin&&(c=l),v.cacheWillUpdate&&g++);0===g?this.plugins.push(e.defaultPrecacheCacheabilityPlugin):1<g&&null!==c&&this.plugins.splice(c,
1)}}e.defaultPrecacheCacheabilityPlugin={async cacheWillUpdate({response:c}){return!c||400<=c.status?null:c}};e.copyRedirectedCacheableResponsesPlugin={async cacheWillUpdate({response:c}){return c.redirected?await (0,f.copyResponse)(c):c}}};
shadow$provide[61]=function(m,a,u,h){Object.defineProperties(h,{__esModule:{enumerable:!0,value:!0},PrecacheController:{enumerable:!0,get:function(){return v}}});a(17);var f=a(20);a(13);var b=a(16),d=a(30),e=a(52),c=a(53),g=a(54);a(55);a(56);var l=a(60);a(51);class v{constructor({cacheName:k,plugins:t=[],fallbackToNetwork:w=!0}={}){this._urlsToCacheKeys=new Map;this._urlsToCacheModes=new Map;this._cacheKeysToIntegrities=new Map;this._strategy=new l.PrecacheStrategy({cacheName:f.cacheNames.getPrecacheName(k),
plugins:[...t,new g.PrecacheCacheKeyPlugin({precacheController:this})],fallbackToNetwork:w});this.install=this.install.bind(this);this.activate=this.activate.bind(this)}get strategy(){return this._strategy}precache(k){this.addToCacheList(k);this._installAndActiveListenersAdded||(self.addEventListener("install",this.install),self.addEventListener("activate",this.activate),this._installAndActiveListenersAdded=!0)}addToCacheList(k){const t=[];for(const w of k){"string"===typeof w?t.push(w):w&&void 0===
w.revision&&t.push(w.url);const {cacheKey:B,url:D}=(0,e.createCacheKey)(w);k="string"!==typeof w&&w.revision?"reload":"default";if(this._urlsToCacheKeys.has(D)&&this._urlsToCacheKeys.get(D)!==B)throw new b.WorkboxError("add-to-cache-list-conflicting-entries",{firstEntry:this._urlsToCacheKeys.get(D),secondEntry:B});if("string"!==typeof w&&w.integrity){if(this._cacheKeysToIntegrities.has(B)&&this._cacheKeysToIntegrities.get(B)!==w.integrity)throw new b.WorkboxError("add-to-cache-list-conflicting-integrities",
{url:D});this._cacheKeysToIntegrities.set(B,w.integrity)}this._urlsToCacheKeys.set(D,B);this._urlsToCacheModes.set(D,k);0<t.length&&(k="Workbox is precaching URLs without revision "+`info: ${t.join(", ")}\nThis is generally NOT safe. `+"Learn more at https://bit.ly/wb-precache",console.warn(k))}}install(k){return(0,d.waitUntil)(k,async()=>{const t=new c.PrecacheInstallReportPlugin;this.strategy.plugins.push(t);for(const [x,z]of this._urlsToCacheKeys){var w=this._cacheKeysToIntegrities.get(z);const A=
this._urlsToCacheModes.get(x);w=new Request(x,{integrity:w,cache:A,credentials:"same-origin"});await Promise.all(this.strategy.handleAll({params:{cacheKey:z},request:w,event:k}))}const {updatedURLs:B,notUpdatedURLs:D}=t;return{updatedURLs:B,notUpdatedURLs:D}})}activate(k){return(0,d.waitUntil)(k,async()=>{const t=await self.caches.open(this.strategy.cacheName),w=await t.keys(),B=new Set(this._urlsToCacheKeys.values()),D=[];for(const x of w)B.has(x.url)||(await t.delete(x),D.push(x.url));return{deletedURLs:D}})}getURLsToCacheKeys(){return this._urlsToCacheKeys}getCachedURLs(){return[...this._urlsToCacheKeys.keys()]}getCacheKeyForURL(k){k=
new URL(k,location.href);return this._urlsToCacheKeys.get(k.href)}getIntegrityForCacheKey(k){return this._cacheKeysToIntegrities.get(k)}async matchPrecache(k){if(k=this.getCacheKeyForURL(k instanceof Request?k.url:k))return(await self.caches.open(this.strategy.cacheName)).match(k)}createHandlerBoundToURL(k){const t=this.getCacheKeyForURL(k);if(!t)throw new b.WorkboxError("non-precached-url",{url:k});return w=>{w.request=new Request(k);w.params=Object.assign({cacheKey:t},w.params);return this.strategy.handle(w)}}}
};
shadow$provide[62]=function(m,a,u,h){Object.defineProperties(h,{__esModule:{enumerable:!0,value:!0},getOrCreatePrecacheController:{enumerable:!0,get:function(){return d}}});var f=a(61);a(51);let b;const d=()=>{b||(b=new f.PrecacheController);return b}};
shadow$provide[63]=function(m,a,u,h){function f(d){(0,b.getOrCreatePrecacheController)().strategy.plugins.push(...d)}Object.defineProperties(h,{__esModule:{enumerable:!0,value:!0},addPlugins:{enumerable:!0,get:function(){return f}}});var b=a(62);a(51)};
shadow$provide[64]=function(m,a,u,h){function f(b,d=[]){for(const e of[...b.searchParams.keys()])d.some(c=>c.test(e))&&b.searchParams.delete(e);return b}Object.defineProperties(h,{__esModule:{enumerable:!0,value:!0},removeIgnoredSearchParams:{enumerable:!0,get:function(){return f}}});a(51)};
shadow$provide[65]=function(m,a,u,h){function*f(d,{ignoreURLParametersMatching:e=[/^utm_/,/^fbclid$/],directoryIndex:c="index.html",cleanURLs:g=!0,urlManipulation:l}={}){d=new URL(d,location.href);d.hash="";yield d.href;e=(0,b.removeIgnoredSearchParams)(d,e);yield e.href;if(c&&e.pathname.endsWith("/")){const v=new URL(e.href);v.pathname+=c;yield v.href}g&&(c=new URL(e.href),c.pathname+=".html",yield c.href);if(l){l=l({url:d});for(const v of l)yield v.href}}Object.defineProperties(h,{__esModule:{enumerable:!0,
value:!0},generateURLVariations:{enumerable:!0,get:function(){return f}}});var b=a(64);a(51)};
shadow$provide[66]=function(m,a,u,h){Object.defineProperties(h,{__esModule:{enumerable:!0,value:!0},PrecacheRoute:{enumerable:!0,get:function(){return b}}});a(13);a(27);m=a(42);var f=a(65);a(51);class b extends m.Route{constructor(d,e){super(({request:c})=>{var g=d.getURLsToCacheKeys();for(const l of(0,f.generateURLVariations)(c.url,e))if(c=g.get(l))return g=d.getIntegrityForCacheKey(c),{cacheKey:c,integrity:g}},d.strategy)}}};
shadow$provide[67]=function(m,a,u,h){function f(c){const g=(0,d.getOrCreatePrecacheController)();c=new e.PrecacheRoute(g,c);(0,b.registerRoute)(c)}Object.defineProperties(h,{__esModule:{enumerable:!0,value:!0},addRoute:{enumerable:!0,get:function(){return f}}});var b=a(47),d=a(62),e=a(66);a(51)};
shadow$provide[68]=function(m,a,u,h){Object.defineProperties(h,{__esModule:{enumerable:!0,value:!0},deleteOutdatedCaches:{enumerable:!0,get:function(){return f}}});a(51);const f=async(b,d="-precache-")=>{const e=(await self.caches.keys()).filter(c=>c.includes(d)&&c.includes(self.registration.scope)&&c!==b);await Promise.all(e.map(c=>self.caches.delete(c)));return e}};
shadow$provide[69]=function(m,a,u,h){function f(){self.addEventListener("activate",e=>{const c=b.cacheNames.getPrecacheName();e.waitUntil((0,d.deleteOutdatedCaches)(c).then(g=>{}))})}Object.defineProperties(h,{__esModule:{enumerable:!0,value:!0},cleanupOutdatedCaches:{enumerable:!0,get:function(){return f}}});var b=a(20);a(13);var d=a(68);a(51)};
shadow$provide[70]=function(m,a,u,h){function f(d){return(0,b.getOrCreatePrecacheController)().createHandlerBoundToURL(d)}Object.defineProperties(h,{__esModule:{enumerable:!0,value:!0},createHandlerBoundToURL:{enumerable:!0,get:function(){return f}}});var b=a(62);a(51)};
shadow$provide[71]=function(m,a,u,h){function f(d){return(0,b.getOrCreatePrecacheController)().getCacheKeyForURL(d)}Object.defineProperties(h,{__esModule:{enumerable:!0,value:!0},getCacheKeyForURL:{enumerable:!0,get:function(){return f}}});var b=a(62);a(51)};
shadow$provide[72]=function(m,a,u,h){function f(d){return(0,b.getOrCreatePrecacheController)().matchPrecache(d)}Object.defineProperties(h,{__esModule:{enumerable:!0,value:!0},matchPrecache:{enumerable:!0,get:function(){return f}}});var b=a(62);a(51)};
shadow$provide[73]=function(m,a,u,h){function f(d){(0,b.getOrCreatePrecacheController)().precache(d)}Object.defineProperties(h,{__esModule:{enumerable:!0,value:!0},precache:{enumerable:!0,get:function(){return f}}});var b=a(62);a(51)};
shadow$provide[74]=function(m,a,u,h){function f(e,c){(0,d.precache)(e);(0,b.addRoute)(c)}Object.defineProperties(h,{__esModule:{enumerable:!0,value:!0},precacheAndRoute:{enumerable:!0,get:function(){return f}}});var b=a(67),d=a(73);a(51)};
shadow$provide[75]=function(m,a,u,h){Object.defineProperties(h,{__esModule:{enumerable:!0,value:!0},PrecacheFallbackPlugin:{enumerable:!0,get:function(){return b}}});var f=a(62);a(51);class b{constructor({fallbackURL:d,precacheController:e}){this.handlerDidError=()=>this._precacheController.matchPrecache(this._fallbackURL);this._fallbackURL=d;this._precacheController=e||(0,f.getOrCreatePrecacheController)()}}};
shadow$provide[76]=function(m,a,u,h){a(51)};
shadow$provide[77]=function(m,a,u,h){Object.defineProperties(h,{__esModule:{enumerable:!0,value:!0},PrecacheController:{enumerable:!0,get:function(){return k.PrecacheController}},PrecacheFallbackPlugin:{enumerable:!0,get:function(){return B.PrecacheFallbackPlugin}},PrecacheRoute:{enumerable:!0,get:function(){return t.PrecacheRoute}},PrecacheStrategy:{enumerable:!0,get:function(){return w.PrecacheStrategy}},addPlugins:{enumerable:!0,get:function(){return f.addPlugins}},addRoute:{enumerable:!0,get:function(){return b.addRoute}},
cleanupOutdatedCaches:{enumerable:!0,get:function(){return d.cleanupOutdatedCaches}},createHandlerBoundToURL:{enumerable:!0,get:function(){return e.createHandlerBoundToURL}},getCacheKeyForURL:{enumerable:!0,get:function(){return c.getCacheKeyForURL}},matchPrecache:{enumerable:!0,get:function(){return g.matchPrecache}},precache:{enumerable:!0,get:function(){return l.precache}},precacheAndRoute:{enumerable:!0,get:function(){return v.precacheAndRoute}}});var f=a(63),b=a(67),d=a(69),e=a(70),c=a(71),g=
a(72),l=a(73),v=a(74),k=a(61),t=a(66),w=a(60),B=a(75);a(51);m=a(76);a.exportCopy(u,m)};
shadow$provide[78]=function(m,a,u,h){Object.defineProperties(h,{__esModule:{enumerable:!0,value:!0},messages:{enumerable:!0,get:function(){return d}}});var f=a(13),b=a(27);a(57);const d={strategyStart:(e,c)=>`Using ${e} to respond to '${(0,b.getFriendlyURL)(c.url)}'`,printFinalResponse:e=>{e&&(f.logger.groupCollapsed("View the final response here."),f.logger.log(e||"[No response returned]"),f.logger.groupEnd())}}};
shadow$provide[79]=function(m,a,u,h){Object.defineProperties(h,{__esModule:{enumerable:!0,value:!0},CacheFirst:{enumerable:!0,get:function(){return b}}});a(17);a(13);var f=a(16);m=a(59);a(78);a(57);class b extends m.Strategy{async _handle(d,e){let c=await e.cacheMatch(d),g=void 0;if(!c)try{c=await e.fetchAndCachePut(d)}catch(l){l instanceof Error&&(g=l)}if(!c)throw new f.WorkboxError("no-response",{url:d.url,error:g});return c}}};
shadow$provide[80]=function(m,a,u,h){Object.defineProperties(h,{__esModule:{enumerable:!0,value:!0},CacheOnly:{enumerable:!0,get:function(){return b}}});a(17);a(13);var f=a(16);m=a(59);a(78);a(57);class b extends m.Strategy{async _handle(d,e){e=await e.cacheMatch(d);if(!e)throw new f.WorkboxError("no-response",{url:d.url});return e}}};
shadow$provide[81]=function(m,a,u,h){Object.defineProperties(h,{__esModule:{enumerable:!0,value:!0},cacheOkAndOpaquePlugin:{enumerable:!0,get:function(){return f}}});a(57);const f={cacheWillUpdate:async({response:b})=>200===b.status||0===b.status?b:null}};
shadow$provide[82]=function(m,a,u,h){Object.defineProperties(h,{__esModule:{enumerable:!0,value:!0},NetworkFirst:{enumerable:!0,get:function(){return d}}});a(17);a(13);var f=a(16),b=a(81);m=a(59);a(78);a(57);class d extends m.Strategy{constructor(e={}){super(e);this.plugins.some(c=>"cacheWillUpdate"in c)||this.plugins.unshift(b.cacheOkAndOpaquePlugin);this._networkTimeoutSeconds=e.networkTimeoutSeconds||0}async _handle(e,c){var g=[];const l=[];let v;if(this._networkTimeoutSeconds){const {id:t,promise:w}=
this._getTimeoutPromise({request:e,logs:g,handler:c});v=t;l.push(w)}const k=this._getNetworkPromise({timeoutId:v,request:e,logs:g,handler:c});l.push(k);g=await c.waitUntil((async()=>await c.waitUntil(Promise.race(l))||await k)());if(!g)throw new f.WorkboxError("no-response",{url:e.url});return g}_getTimeoutPromise({request:e,handler:c}){let g;return{promise:new Promise(l=>{g=setTimeout(async()=>{l(await c.cacheMatch(e))},1E3*this._networkTimeoutSeconds)}),id:g}}async _getNetworkPromise({timeoutId:e,
request:c,handler:g}){let l,v;try{v=await g.fetchAndCachePut(c)}catch(k){k instanceof Error&&(l=k)}e&&clearTimeout(e);if(l||!v)v=await g.cacheMatch(c);return v}}};
shadow$provide[83]=function(m,a,u,h){Object.defineProperties(h,{__esModule:{enumerable:!0,value:!0},NetworkOnly:{enumerable:!0,get:function(){return d}}});a(17);a(13);var f=a(28),b=a(16);m=a(59);a(78);a(57);class d extends m.Strategy{constructor(e={}){super(e);this._networkTimeoutSeconds=e.networkTimeoutSeconds||0}async _handle(e,c){let g=void 0,l;try{const v=[c.fetch(e)];if(this._networkTimeoutSeconds){const k=(0,f.timeout)(1E3*this._networkTimeoutSeconds);v.push(k)}l=await Promise.race(v);if(!l)throw Error("Timed out the network response after "+
`${this._networkTimeoutSeconds} seconds.`);}catch(v){v instanceof Error&&(g=v)}if(!l)throw new b.WorkboxError("no-response",{url:e.url,error:g});return l}}};
shadow$provide[84]=function(m,a,u,h){Object.defineProperties(h,{__esModule:{enumerable:!0,value:!0},StaleWhileRevalidate:{enumerable:!0,get:function(){return d}}});a(17);a(13);var f=a(16),b=a(81);m=a(59);a(78);a(57);class d extends m.Strategy{constructor(e={}){super(e);this.plugins.some(c=>"cacheWillUpdate"in c)||this.plugins.unshift(b.cacheOkAndOpaquePlugin)}async _handle(e,c){const g=c.fetchAndCachePut(e).catch(()=>{});void c.waitUntil(g);c=await c.cacheMatch(e);let l;if(!c)try{c=await g}catch(v){v instanceof
Error&&(l=v)}if(!c)throw new f.WorkboxError("no-response",{url:e.url,error:l});return c}}};
shadow$provide[85]=function(m,a,u,h){Object.defineProperties(h,{__esModule:{enumerable:!0,value:!0},CacheFirst:{enumerable:!0,get:function(){return f.CacheFirst}},CacheOnly:{enumerable:!0,get:function(){return b.CacheOnly}},NetworkFirst:{enumerable:!0,get:function(){return d.NetworkFirst}},NetworkOnly:{enumerable:!0,get:function(){return e.NetworkOnly}},StaleWhileRevalidate:{enumerable:!0,get:function(){return c.StaleWhileRevalidate}},Strategy:{enumerable:!0,get:function(){return g.Strategy}},StrategyHandler:{enumerable:!0,
get:function(){return l.StrategyHandler}}});var f=a(79),b=a(80),d=a(82),e=a(83),c=a(84),g=a(59),l=a(58);a(57)};
'use strict';$APP.kg(11,{});var sN=$APP.kg(38,{});var tN=$APP.kg(50,{});var uN=$APP.kg(77,{});var vN=$APP.kg(85,{});var wN=$APP.Ig($APP.Rf.g(function(a){return["/wiki-guides",$APP.r.h(a)].join("")},new $APP.S(null,15,5,$APP.T,"/index.html /assets/re-com/css/bootstrap.css /assets/re-com/css/material-design-iconic-font.min.css /assets/re-com/css/re-com.css /assets/re-com/css/chosen-sprite.png /assets/re-com/css/chosen-sprite@2x.png /assets/re-com/fonts/Material-Design-Iconic-Font.eot /assets/re-com/fonts/Material-Design-Iconic-Font.svg /assets/re-com/fonts/Material-Design-Iconic-Font.ttf /assets/re-com/fonts/Material-Design-Iconic-Font.woff /assets/re-com/fonts/Material-Design-Iconic-Font.woff2 /assets/re-com/scripts/detect-element-resize.js /assets/css/app.css /shared.js /app.js".split(" "),
null)));self.addEventListener("install",function(a){return a.waitUntil(caches.open(sN.cacheNames.runtime).then(function(b){return b.addAll(wN)}))});self.addEventListener("message",function(a){a=null==a?null:a.data;return $APP.I.g(null==a?null:a.type,"SKIP_WAITING")?self.skipWaiting():null});tN.registerRoute(function(a){return $APP.I.g(a.request.destination,"image")},new vN.CacheFirst);tN.setDefaultHandler(new vN.StaleWhileRevalidate);uN.precacheAndRoute([{url:"/wiki-guides/index.html",revision:"65503d1e2f5da60fbc9c18d3730db1d3ed24f2bd280c9ae23db4584425efe7c9"}]);
tN.registerRoute(new tN.NavigationRoute(uN.createHandlerBoundToURL("/wiki-guides/index.html")));
}).call(this);