importScripts("shared.js");
(function(){
shadow$provide[12]=function(n,g,C,p){n=function(l){function k(G,H,m){Object.defineProperty(G,H,{value:m,enumerable:!0,configurable:!0,writable:!0});return G[H]}function t(G,H,m,z){H=Object.create((H&&H.prototype instanceof q?H:q).prototype);z=new Q(z||[]);ba(H,"_invoke",{value:K(G,m,z)});return H}function v(G,H,m){try{return{type:"normal",arg:G.call(H,m)}}catch(z){return{type:"throw",arg:z}}}function q(){}function x(){}function E(){}function P(G){["next","throw","return"].forEach(function(H){k(G,
H,function(m){return this._invoke(H,m)})})}function B(G,H){function m(F,S,U,la){F=v(G[F],G,S);if("throw"===F.type)la(F.arg);else{var ma=F.arg;return(F=ma.value)&&"object"===typeof F&&ia.call(F,"__await")?H.resolve(F.__await).then(function(na){m("next",na,U,la)},function(na){m("throw",na,U,la)}):H.resolve(F).then(function(na){ma.value=na;U(ma)},function(na){return m("throw",na,U,la)})}}var z;ba(this,"_invoke",{value:function(F,S){function U(){return new H(function(la,ma){m(F,S,la,ma)})}return z=z?
z.then(U,U):U()}})}function K(G,H,m){var z=ya;return function(F,S){if(z===Pa)throw Error("Generator is already running");if(z===Ga){if("throw"===F)throw S;return{value:aa,done:!0}}m.method=F;for(m.arg=S;;){if(F=m.delegate)if(F=N(F,m)){if(F===ta)continue;return F}if("next"===m.method)m.sent=m._sent=m.arg;else if("throw"===m.method){if(z===ya)throw z=Ga,m.arg;m.dispatchException(m.arg)}else"return"===m.method&&m.abrupt("return",m.arg);z=Pa;F=v(G,H,m);if("normal"===F.type){z=m.done?Ga:Ca;if(F.arg===
ta)continue;return{value:F.arg,done:m.done}}"throw"===F.type&&(z=Ga,m.method="throw",m.arg=F.arg)}}}function N(G,H){var m=H.method,z=G.iterator[m];if(z===aa){H.delegate=null;if("throw"===m&&G.iterator["return"]&&(H.method="return",H.arg=aa,N(G,H),"throw"===H.method))return ta;"return"!==m&&(H.method="throw",H.arg=new TypeError("The iterator does not provide a '"+m+"' method"));return ta}m=v(z,G.iterator,H.arg);if("throw"===m.type)return H.method="throw",H.arg=m.arg,H.delegate=null,ta;m=m.arg;if(!m)return H.method=
"throw",H.arg=new TypeError("iterator result is not an object"),H.delegate=null,ta;if(m.done)H[G.resultName]=m.value,H.next=G.nextLoc,"return"!==H.method&&(H.method="next",H.arg=aa);else return m;H.delegate=null;return ta}function ea(G){var H={tryLoc:G[0]};1 in G&&(H.catchLoc=G[1]);2 in G&&(H.finallyLoc=G[2],H.afterLoc=G[3]);this.tryEntries.push(H)}function fa(G){var H=G.completion||{};H.type="normal";delete H.arg;G.completion=H}function Q(G){this.tryEntries=[{tryLoc:"root"}];G.forEach(ea,this);this.reset(!0)}
function W(G){if(null!=G){var H=G[ja];if(H)return H.call(G);if("function"===typeof G.next)return G;if(!isNaN(G.length)){var m=-1;H=function F(){for(;++m<G.length;)if(ia.call(G,m))return F.value=G[m],F.done=!1,F;F.value=aa;F.done=!0;return F};return H.next=H}}throw new TypeError(typeof G+" is not iterable");}var T=Object.prototype,ia=T.hasOwnProperty,ba=Object.defineProperty||function(G,H,m){G[H]=m.value},aa,L="function"===typeof Symbol?Symbol:{},ja=L.iterator||"@@iterator",ka=L.asyncIterator||"@@asyncIterator",
qa=L.toStringTag||"@@toStringTag";try{k({},"")}catch(G){k=function(H,m,z){return H[m]=z}}l.wrap=t;var ya="suspendedStart",Ca="suspendedYield",Pa="executing",Ga="completed",ta={};L={};k(L,ja,function(){return this});var Oa=Object.getPrototypeOf;(Oa=Oa&&Oa(Oa(W([]))))&&Oa!==T&&ia.call(Oa,ja)&&(L=Oa);var Ya=E.prototype=q.prototype=Object.create(L);x.prototype=E;ba(Ya,"constructor",{value:E,configurable:!0});ba(E,"constructor",{value:x,configurable:!0});x.displayName=k(E,qa,"GeneratorFunction");l.isGeneratorFunction=
function(G){return(G="function"===typeof G&&G.constructor)?G===x||"GeneratorFunction"===(G.displayName||G.name):!1};l.mark=function(G){Object.setPrototypeOf?Object.setPrototypeOf(G,E):(G.__proto__=E,k(G,qa,"GeneratorFunction"));G.prototype=Object.create(Ya);return G};l.awrap=function(G){return{__await:G}};P(B.prototype);k(B.prototype,ka,function(){return this});l.AsyncIterator=B;l.async=function(G,H,m,z,F){void 0===F&&(F=Promise);var S=new B(t(G,H,m,z),F);return l.isGeneratorFunction(H)?S:S.next().then(function(U){return U.done?
U.value:S.next()})};P(Ya);k(Ya,qa,"Generator");k(Ya,ja,function(){return this});k(Ya,"toString",function(){return"[object Generator]"});l.keys=function(G){var H=Object(G),m=[],z;for(z in H)m.push(z);m.reverse();return function S(){for(;m.length;){var U=m.pop();if(U in H)return S.value=U,S.done=!1,S}S.done=!0;return S}};l.values=W;Q.prototype={constructor:Q,reset:function(G){this.next=this.prev=0;this.sent=this._sent=aa;this.done=!1;this.delegate=null;this.method="next";this.arg=aa;this.tryEntries.forEach(fa);
if(!G)for(var H in this)"t"===H.charAt(0)&&ia.call(this,H)&&!isNaN(+H.slice(1))&&(this[H]=aa)},stop:function(){this.done=!0;var G=this.tryEntries[0].completion;if("throw"===G.type)throw G.arg;return this.rval},dispatchException:function(G){function H(ma,na){S.type="throw";S.arg=G;m.next=ma;na&&(m.method="next",m.arg=aa);return!!na}if(this.done)throw G;for(var m=this,z=this.tryEntries.length-1;0<=z;--z){var F=this.tryEntries[z],S=F.completion;if("root"===F.tryLoc)return H("end");if(F.tryLoc<=this.prev){var U=
ia.call(F,"catchLoc"),la=ia.call(F,"finallyLoc");if(U&&la){if(this.prev<F.catchLoc)return H(F.catchLoc,!0);if(this.prev<F.finallyLoc)return H(F.finallyLoc)}else if(U){if(this.prev<F.catchLoc)return H(F.catchLoc,!0)}else if(la){if(this.prev<F.finallyLoc)return H(F.finallyLoc)}else throw Error("try statement without catch or finally");}}},abrupt:function(G,H){for(var m=this.tryEntries.length-1;0<=m;--m){var z=this.tryEntries[m];if(z.tryLoc<=this.prev&&ia.call(z,"finallyLoc")&&this.prev<z.finallyLoc){var F=
z;break}}F&&("break"===G||"continue"===G)&&F.tryLoc<=H&&H<=F.finallyLoc&&(F=null);m=F?F.completion:{};m.type=G;m.arg=H;return F?(this.method="next",this.next=F.finallyLoc,ta):this.complete(m)},complete:function(G,H){if("throw"===G.type)throw G.arg;"break"===G.type||"continue"===G.type?this.next=G.arg:"return"===G.type?(this.rval=this.arg=G.arg,this.method="return",this.next="end"):"normal"===G.type&&H&&(this.next=H);return ta},finish:function(G){for(var H=this.tryEntries.length-1;0<=H;--H){var m=
this.tryEntries[H];if(m.finallyLoc===G)return this.complete(m.completion,m.afterLoc),fa(m),ta}},"catch":function(G){for(var H=this.tryEntries.length-1;0<=H;--H){var m=this.tryEntries[H];if(m.tryLoc===G){G=m.completion;if("throw"===G.type){var z=G.arg;fa(m)}return z}}throw Error("illegal catch attempt");},delegateYield:function(G,H,m){this.delegate={iterator:W(G),resultName:H,nextLoc:m};"next"===this.method&&(this.arg=aa);return ta}};return l}("object"===typeof C?C.exports:{});try{regeneratorRuntime=
n}catch(l){"object"===typeof globalThis?globalThis.regeneratorRuntime=n:Function("r","regeneratorRuntime \x3d r")(n)}};
shadow$provide[13]=function(n,g,C,p){try{self["workbox:core:7.0.0"]&&_()}catch(l){}};
shadow$provide[14]=function(n,g,C,p){Object.defineProperties(p,{__esModule:{enumerable:!0,value:!0},logger:{enumerable:!0,get:function(){return null}}});g(13)};
shadow$provide[15]=function(n,g,C,p){Object.defineProperties(p,{__esModule:{enumerable:!0,value:!0},messages:{enumerable:!0,get:function(){return l}}});g(13);const l={"invalid-value":({paramName:k,validValueDescription:t,value:v})=>{if(!k||!t)throw Error("Unexpected input to 'invalid-value' error.");return`The '${k}' parameter was given a value with an `+`unexpected value. ${t} Received a value of `+`${JSON.stringify(v)}.`},"not-an-array":({moduleName:k,className:t,funcName:v,paramName:q})=>{if(!(k&&
t&&v&&q))throw Error("Unexpected input to 'not-an-array' error.");return`The parameter '${q}' passed into `+`'${k}.${t}.${v}()' must be an array.`},"incorrect-type":({expectedType:k,paramName:t,moduleName:v,className:q,funcName:x})=>{if(!(k&&t&&v&&x))throw Error("Unexpected input to 'incorrect-type' error.");return`The parameter '${t}' passed into `+`'${v}.${q?`${q}.`:""}`+`${x}()' must be of type ${k}.`},"incorrect-class":({expectedClassName:k,paramName:t,moduleName:v,className:q,funcName:x,isReturnValueProblem:E})=>
{if(!k||!v||!x)throw Error("Unexpected input to 'incorrect-class' error.");q=q?`${q}.`:"";return E?"The return value from "+`'${v}.${q}${x}()' `+`must be an instance of class ${k}.`:`The parameter '${t}' passed into `+`'${v}.${q}${x}()' `+`must be an instance of class ${k}.`},"missing-a-method":({expectedMethod:k,paramName:t,moduleName:v,className:q,funcName:x})=>{if(!(k&&t&&v&&q&&x))throw Error("Unexpected input to 'missing-a-method' error.");return`${v}.${q}.${x}() expected the `+`'${t}' parameter to expose a '${k}' method.`},
"add-to-cache-list-unexpected-type":({entry:k})=>"An unexpected entry was passed to 'workbox-precaching.PrecacheController.addToCacheList()' The entry "+`'${JSON.stringify(k)}' isn't supported. You must supply an array of `+"strings with one or more characters, objects with a url property or Request objects.","add-to-cache-list-conflicting-entries":({firstEntry:k,secondEntry:t})=>{if(!k||!t)throw Error("Unexpected input to 'add-to-cache-list-duplicate-entries' error.");return"Two of the entries passed to 'workbox-precaching.PrecacheController.addToCacheList()' had the URL "+
`${k} but different revision details. Workbox is `+"unable to cache and version the asset correctly. Please remove one of the entries."},"plugin-error-request-will-fetch":({thrownErrorMessage:k})=>{if(!k)throw Error("Unexpected input to 'plugin-error-request-will-fetch', error.");return"An error was thrown by a plugins 'requestWillFetch()' method. "+`The thrown error message was: '${k}'.`},"invalid-cache-name":({cacheNameId:k,value:t})=>{if(!k)throw Error("Expected a 'cacheNameId' for error 'invalid-cache-name'");
return"You must provide a name containing at least one character for "+`setCacheDetails({${k}: '...'}). Received a value of `+`'${JSON.stringify(t)}'`},"unregister-route-but-not-found-with-method":({method:k})=>{if(!k)throw Error("Unexpected input to 'unregister-route-but-not-found-with-method' error.");return"The route you're trying to unregister was not  previously "+`registered for the method type '${k}'.`},"unregister-route-route-not-registered":()=>"The route you're trying to unregister was not previously registered.",
"queue-replay-failed":({name:k})=>`Replaying the background sync queue '${k}' failed.`,"duplicate-queue-name":({name:k})=>`The Queue name '${k}' is already being used. `+"All instances of backgroundSync.Queue must be given unique names.","expired-test-without-max-age":({methodName:k,paramName:t})=>`The '${k}()' method can only be used when the `+`'${t}' is used in the constructor.`,"unsupported-route-type":({moduleName:k,className:t,funcName:v,paramName:q})=>`The supplied '${q}' parameter was an unsupported type. `+
`Please check the docs for ${k}.${t}.${v} for `+"valid input types.","not-array-of-class":({value:k,expectedClass:t,moduleName:v,className:q,funcName:x,paramName:E})=>`The supplied '${E}' parameter must be an array of `+`'${t}' objects. Received '${JSON.stringify(k)},'. `+`Please check the call to ${v}.${q}.${x}() `+"to fix the issue.","max-entries-or-age-required":({moduleName:k,className:t,funcName:v})=>"You must define either config.maxEntries or config.maxAgeSeconds"+`in ${k}.${t}.${v}`,"statuses-or-headers-required":({moduleName:k,
className:t,funcName:v})=>"You must define either config.statuses or config.headers"+`in ${k}.${t}.${v}`,"invalid-string":({moduleName:k,funcName:t,paramName:v})=>{if(!v||!k||!t)throw Error("Unexpected input to 'invalid-string' error.");return`When using strings, the '${v}' parameter must start with `+"'http' (for cross-origin matches) or '/' (for same-origin matches). "+`Please see the docs for ${k}.${t}() for `+"more info."},"channel-name-required":()=>"You must provide a channelName to construct a BroadcastCacheUpdate instance.",
"invalid-responses-are-same-args":()=>"The arguments passed into responsesAreSame() appear to be invalid. Please ensure valid Responses are used.","expire-custom-caches-only":()=>"You must provide a 'cacheName' property when using the expiration plugin with a runtime caching strategy.","unit-must-be-bytes":({normalizedRangeHeader:k})=>{if(!k)throw Error("Unexpected input to 'unit-must-be-bytes' error.");return"The 'unit' portion of the Range header must be set to 'bytes'. "+`The Range header provided was "${k}"`},
"single-range-only":({normalizedRangeHeader:k})=>{if(!k)throw Error("Unexpected input to 'single-range-only' error.");return"Multiple ranges are not supported. Please use a  single start value, and optional end value. The Range header provided was "+`"${k}"`},"invalid-range-values":({normalizedRangeHeader:k})=>{if(!k)throw Error("Unexpected input to 'invalid-range-values' error.");return"The Range header is missing both start and end values. At least one of those values is needed. The Range header provided was "+
`"${k}"`},"no-range-header":()=>"No Range header was found in the Request provided.","range-not-satisfiable":({size:k,start:t,end:v})=>`The start (${t}) and end (${v}) values in the Range are `+`not satisfiable by the cached response, which is ${k} bytes.`,"attempt-to-cache-non-get-request":({url:k,method:t})=>`Unable to cache '${k}' because it is a '${t}' request and `+"only 'GET' requests can be cached.","cache-put-with-no-response":({url:k})=>`There was an attempt to cache '${k}' but the response was not `+
"defined.","no-response":({url:k,error:t})=>{k=`The strategy could not generate a response for '${k}'.`;t&&(k+=` The underlying error is ${t}.`);return k},"bad-precaching-response":({url:k,status:t})=>`The precaching request for '${k}' failed`+(t?` with an HTTP status of ${t}.`:"."),"non-precached-url":({url:k})=>`createHandlerBoundToURL('${k}') was called, but that URL is `+"not precached. Please pass in a URL that is precached instead.","add-to-cache-list-conflicting-integrities":({url:k})=>"Two of the entries passed to 'workbox-precaching.PrecacheController.addToCacheList()' had the URL "+
`${k} with different integrity values. Please remove one of them.`,"missing-precache-entry":({cacheName:k,url:t})=>`Unable to find a precached response in ${k} for ${t}.`,"cross-origin-copy-response":({origin:k})=>"workbox-core.copyResponse() can only be used with same-origin "+`responses. It was passed a response with origin ${k}.`,"opaque-streams-source":({type:k})=>{const t="One of the workbox-streams sources resulted in an "+`'${k}' response.`;return"opaqueredirect"===k?`${t} Please do not use a navigation request that results `+
"in a redirect as a source.":`${t} Please ensure your sources are CORS-enabled.`}}};
shadow$provide[16]=function(n,g,C,p){Object.defineProperties(p,{__esModule:{enumerable:!0,value:!0},messageGenerator:{enumerable:!0,get:function(){return l}}});g(15);g(13);const l=(k,...t)=>{0<t.length&&(k+=` :: ${JSON.stringify(t)}`);return k}};
shadow$provide[17]=function(n,g,C,p){Object.defineProperties(p,{__esModule:{enumerable:!0,value:!0},WorkboxError:{enumerable:!0,get:function(){return k}}});var l=g(16);g(13);class k extends Error{constructor(t,v){super((0,l.messageGenerator)(t,v));this.name=t;this.details=v}}};
shadow$provide[18]=function(n,g,C,p){Object.defineProperties(p,{__esModule:{enumerable:!0,value:!0},assert:{enumerable:!0,get:function(){return null}}});g(17);g(13)};
shadow$provide[19]=function(n,g,C,p){Object.defineProperties(p,{__esModule:{enumerable:!0,value:!0},quotaErrorCallbacks:{enumerable:!0,get:function(){return l}}});g(13);const l=new Set};
shadow$provide[20]=function(n,g,C,p){function l(t){k.quotaErrorCallbacks.add(t)}Object.defineProperties(p,{__esModule:{enumerable:!0,value:!0},registerQuotaErrorCallback:{enumerable:!0,get:function(){return l}}});g(14);g(18);var k=g(19);g(13)};
shadow$provide[21]=function(n,g,C,p){Object.defineProperties(p,{__esModule:{enumerable:!0,value:!0},cacheNames:{enumerable:!0,get:function(){return v}}});g(13);const l={googleAnalytics:"googleAnalytics",precache:"precache-v2",prefix:"workbox",runtime:"runtime",suffix:"undefined"!==typeof registration?registration.scope:""},k=q=>[l.prefix,q,l.suffix].filter(x=>x&&0<x.length).join("-"),t=q=>{for(const x of Object.keys(l))q(x)},v={updateDetails:q=>{t(x=>{"string"===typeof q[x]&&(l[x]=q[x])})},getGoogleAnalyticsName:q=>
q||k(l.googleAnalytics),getPrecacheName:q=>q||k(l.precache),getPrefix:()=>l.prefix,getRuntimeName:q=>q||k(l.runtime),getSuffix:()=>l.suffix}};
shadow$provide[22]=function(n,g,C,p){function l(t,v){t=new URL(t);for(const q of v)t.searchParams.delete(q);return t.href}async function k(t,v,q,x){const E=l(v.url,q);if(v.url===E)return t.match(v,x);const P=Object.assign(Object.assign({},x),{ignoreSearch:!0});v=await t.keys(v,P);for(const B of v)if(v=l(B.url,q),E===v)return t.match(B,x)}Object.defineProperties(p,{__esModule:{enumerable:!0,value:!0},cacheMatchIgnoreParams:{enumerable:!0,get:function(){return k}}});g(13)};
shadow$provide[23]=function(n,g,C,p){function l(){if(void 0===k)try{new ReadableStream({start(){}}),k=!0}catch(t){k=!1}return k}Object.defineProperties(p,{__esModule:{enumerable:!0,value:!0},canConstructReadableStream:{enumerable:!0,get:function(){return l}}});g(13);let k};
shadow$provide[24]=function(n,g,C,p){function l(){if(void 0===k){const t=new Response("");if("body"in t)try{new Response(t.body),k=!0}catch(v){k=!1}k=!1}return k}Object.defineProperties(p,{__esModule:{enumerable:!0,value:!0},canConstructResponseFromBodyStream:{enumerable:!0,get:function(){return l}}});g(13);let k};
shadow$provide[25]=function(n,g,C,p){function l(k){void k.then(()=>{})}Object.defineProperties(p,{__esModule:{enumerable:!0,value:!0},dontWaitFor:{enumerable:!0,get:function(){return l}}});g(13)};
shadow$provide[26]=function(n,g,C,p){Object.defineProperties(p,{__esModule:{enumerable:!0,value:!0},Deferred:{enumerable:!0,get:function(){return l}}});g(13);class l{constructor(){this.promise=new Promise((k,t)=>{this.resolve=k;this.reject=t})}}};
shadow$provide[27]=function(n,g,C,p){async function l(){for(const t of k.quotaErrorCallbacks)await t()}Object.defineProperties(p,{__esModule:{enumerable:!0,value:!0},executeQuotaErrorCallbacks:{enumerable:!0,get:function(){return l}}});g(14);var k=g(19);g(13)};
shadow$provide[28]=function(n,g,C,p){Object.defineProperties(p,{__esModule:{enumerable:!0,value:!0},getFriendlyURL:{enumerable:!0,get:function(){return l}}});g(13);const l=k=>(new URL(String(k),location.href)).href.replace(new RegExp(`^${location.origin}`),"")};
shadow$provide[29]=function(n,g,C,p){function l(k){return new Promise(t=>setTimeout(t,k))}Object.defineProperties(p,{__esModule:{enumerable:!0,value:!0},timeout:{enumerable:!0,get:function(){return l}}});g(13)};
shadow$provide[30]=function(n,g,C,p){async function l(t){if(t){for(var v=await self.clients.matchAll({type:"window"}),q=new Set(v.map(P=>P.id)),x,E=performance.now();2E3>performance.now()-E;){v=await self.clients.matchAll({type:"window"});if(x=v.find(P=>t?P.id===t:!q.has(P.id)))break;await (0,k.timeout)(100)}return x}}Object.defineProperties(p,{__esModule:{enumerable:!0,value:!0},resultingClientExists:{enumerable:!0,get:function(){return l}}});var k=g(29);g(13)};
shadow$provide[31]=function(n,g,C,p){function l(k,t){t=t();k.waitUntil(t);return t}Object.defineProperties(p,{__esModule:{enumerable:!0,value:!0},waitUntil:{enumerable:!0,get:function(){return l}}});g(13)};
shadow$provide[32]=function(n,g,C,p){Object.defineProperties(p,{__esModule:{enumerable:!0,value:!0},Deferred:{enumerable:!0,get:function(){return E.Deferred}},WorkboxError:{enumerable:!0,get:function(){return Q.WorkboxError}},assert:{enumerable:!0,get:function(){return l.assert}},cacheMatchIgnoreParams:{enumerable:!0,get:function(){return t.cacheMatchIgnoreParams}},cacheNames:{enumerable:!0,get:function(){return k.cacheNames}},canConstructReadableStream:{enumerable:!0,get:function(){return v.canConstructReadableStream}},
canConstructResponseFromBodyStream:{enumerable:!0,get:function(){return q.canConstructResponseFromBodyStream}},dontWaitFor:{enumerable:!0,get:function(){return x.dontWaitFor}},executeQuotaErrorCallbacks:{enumerable:!0,get:function(){return P.executeQuotaErrorCallbacks}},getFriendlyURL:{enumerable:!0,get:function(){return B.getFriendlyURL}},logger:{enumerable:!0,get:function(){return K.logger}},resultingClientExists:{enumerable:!0,get:function(){return N.resultingClientExists}},timeout:{enumerable:!0,
get:function(){return ea.timeout}},waitUntil:{enumerable:!0,get:function(){return fa.waitUntil}}});var l=g(18),k=g(21),t=g(22),v=g(23),q=g(24),x=g(25),E=g(26),P=g(27),B=g(28),K=g(14),N=g(30),ea=g(29),fa=g(31),Q=g(17);g(13)};
shadow$provide[33]=function(n,g,C,p){Object.defineProperties(p,{__esModule:{enumerable:!0,value:!0},cacheNames:{enumerable:!0,get:function(){return k}}});var l=g(21);g(13);const k={get googleAnalytics(){return l.cacheNames.getGoogleAnalyticsName()},get precache(){return l.cacheNames.getPrecacheName()},get prefix(){return l.cacheNames.getPrefix()},get runtime(){return l.cacheNames.getRuntimeName()},get suffix(){return l.cacheNames.getSuffix()}}};
shadow$provide[34]=function(n,g,C,p){async function l(v,q){var x=null;v.url&&(x=(new URL(v.url)).origin);if(x!==self.location.origin)throw new t.WorkboxError("cross-origin-copy-response",{origin:x});v=v.clone();x={headers:new Headers(v.headers),status:v.status,statusText:v.statusText};q=q?q(x):x;v=(0,k.canConstructResponseFromBodyStream)()?v.body:await v.blob();return new Response(v,q)}Object.defineProperties(p,{__esModule:{enumerable:!0,value:!0},copyResponse:{enumerable:!0,get:function(){return l}}});
var k=g(24),t=g(17);g(13)};
shadow$provide[35]=function(n,g,C,p){function l(){self.addEventListener("activate",()=>self.clients.claim())}Object.defineProperties(p,{__esModule:{enumerable:!0,value:!0},clientsClaim:{enumerable:!0,get:function(){return l}}});g(13)};
shadow$provide[36]=function(n,g,C,p){function l(t){k.cacheNames.updateDetails(t)}Object.defineProperties(p,{__esModule:{enumerable:!0,value:!0},setCacheNameDetails:{enumerable:!0,get:function(){return l}}});g(18);var k=g(21);g(17);g(13)};
shadow$provide[37]=function(n,g,C,p){function l(){void self.skipWaiting()}Object.defineProperties(p,{__esModule:{enumerable:!0,value:!0},skipWaiting:{enumerable:!0,get:function(){return l}}});g(14);g(13)};
shadow$provide[38]=function(n,g,C,p){g(13)};
shadow$provide[39]=function(n,g,C,p){Object.defineProperties(p,{__esModule:{enumerable:!0,value:!0},_private:{enumerable:!0,get:function(){return k}},cacheNames:{enumerable:!0,get:function(){return t.cacheNames}},clientsClaim:{enumerable:!0,get:function(){return q.clientsClaim}},copyResponse:{enumerable:!0,get:function(){return v.copyResponse}},registerQuotaErrorCallback:{enumerable:!0,get:function(){return l.registerQuotaErrorCallback}},setCacheNameDetails:{enumerable:!0,get:function(){return x.setCacheNameDetails}},
skipWaiting:{enumerable:!0,get:function(){return E.skipWaiting}}});var l=g(20),k=g(32),t=g(33),v=g(34),q=g(35),x=g(36),E=g(37);g(13);n=g(38);g.exportCopy(C,n)};
shadow$provide[40]=function(n,g,C,p){try{self["workbox:routing:7.0.0"]&&_()}catch(l){}};
shadow$provide[41]=function(n,g,C,p){Object.defineProperties(p,{__esModule:{enumerable:!0,value:!0},defaultMethod:{enumerable:!0,get:function(){return"GET"}},validMethods:{enumerable:!0,get:function(){return l}}});g(40);const l="DELETE GET HEAD PATCH POST PUT".split(" ")};
shadow$provide[42]=function(n,g,C,p){Object.defineProperties(p,{__esModule:{enumerable:!0,value:!0},normalizeHandler:{enumerable:!0,get:function(){return l}}});g(18);g(40);const l=k=>k&&"object"===typeof k?k:{handle:k}};
shadow$provide[43]=function(n,g,C,p){Object.defineProperties(p,{__esModule:{enumerable:!0,value:!0},Route:{enumerable:!0,get:function(){return t}}});g(18);var l=g(41),k=g(42);g(40);class t{constructor(v,q,x=l.defaultMethod){this.handler=(0,k.normalizeHandler)(q);this.match=v;this.method=x}setCatchHandler(v){this.catchHandler=(0,k.normalizeHandler)(v)}}};
shadow$provide[44]=function(n,g,C,p){Object.defineProperties(p,{__esModule:{enumerable:!0,value:!0},NavigationRoute:{enumerable:!0,get:function(){return l}}});g(18);g(14);n=g(43);g(40);class l extends n.Route{constructor(k,{allowlist:t=[/./],denylist:v=[]}={}){super(q=>this._match(q),k);this._allowlist=t;this._denylist=v}_match({url:k,request:t}){if(t&&"navigate"!==t.mode)return!1;const v=k.pathname+k.search;for(const q of this._denylist)if(q.test(v))return!1;return this._allowlist.some(q=>q.test(v))?
!0:!1}}};
shadow$provide[45]=function(n,g,C,p){Object.defineProperties(p,{__esModule:{enumerable:!0,value:!0},RegExpRoute:{enumerable:!0,get:function(){return l}}});g(18);g(14);n=g(43);g(40);class l extends n.Route{constructor(k,t,v){super(({url:q})=>{const x=k.exec(q.href);if(x&&(q.origin===location.origin||0===x.index))return x.slice(1)},t,v)}}};
shadow$provide[46]=function(n,g,C,p){Object.defineProperties(p,{__esModule:{enumerable:!0,value:!0},Router:{enumerable:!0,get:function(){return v}}});g(18);g(28);var l=g(41);g(14);var k=g(42),t=g(17);g(40);class v{constructor(){this._routes=new Map;this._defaultHandlerMap=new Map}get routes(){return this._routes}addFetchListener(){self.addEventListener("fetch",q=>{var {request:x}=q;(x=this.handleRequest({request:x,event:q}))&&q.respondWith(x)})}addCacheListener(){self.addEventListener("message",q=>
{if(q.data&&"CACHE_URLS"===q.data.type){var {payload:x}=q.data;x=Promise.all(x.urlsToCache.map(E=>{"string"===typeof E&&(E=[E]);E=new Request(...E);return this.handleRequest({request:E,event:q})}));q.waitUntil(x);q.ports&&q.ports[0]&&void x.then(()=>q.ports[0].postMessage(!0))}})}handleRequest({request:q,event:x}){const E=new URL(q.url,location.href);if(E.protocol.startsWith("http")){var {params:P,route:B}=this.findMatchingRoute({event:x,request:q,sameOrigin:E.origin===location.origin,url:E}),K=B&&
B.handler,N=q.method;!K&&this._defaultHandlerMap.has(N)&&(K=this._defaultHandlerMap.get(N));if(K){try{var ea=K.handle({url:E,request:q,event:x,params:P})}catch(Q){ea=Promise.reject(Q)}var fa=B&&B.catchHandler;ea instanceof Promise&&(this._catchHandler||fa)&&(ea=ea.catch(async Q=>{if(fa)try{return await fa.handle({url:E,request:q,event:x,params:P})}catch(W){W instanceof Error&&(Q=W)}if(this._catchHandler)return this._catchHandler.handle({url:E,request:q,event:x});throw Q;}));return ea}}}findMatchingRoute({url:q,
sameOrigin:x,request:E,event:P}){var B=this._routes.get(E.method)||[];for(const K of B)if(B=K.match({url:q,sameOrigin:x,request:E,event:P}))return q=B,Array.isArray(q)&&0===q.length?q=void 0:B.constructor===Object&&0===Object.keys(B).length?q=void 0:"boolean"===typeof B&&(q=void 0),{route:K,params:q};return{}}setDefaultHandler(q,x=l.defaultMethod){this._defaultHandlerMap.set(x,(0,k.normalizeHandler)(q))}setCatchHandler(q){this._catchHandler=(0,k.normalizeHandler)(q)}registerRoute(q){this._routes.has(q.method)||
this._routes.set(q.method,[]);this._routes.get(q.method).push(q)}unregisterRoute(q){if(!this._routes.has(q.method))throw new t.WorkboxError("unregister-route-but-not-found-with-method",{method:q.method});const x=this._routes.get(q.method).indexOf(q);if(-1<x)this._routes.get(q.method).splice(x,1);else throw new t.WorkboxError("unregister-route-route-not-registered");}}};
shadow$provide[47]=function(n,g,C,p){Object.defineProperties(p,{__esModule:{enumerable:!0,value:!0},getOrCreateDefaultRouter:{enumerable:!0,get:function(){return t}}});var l=g(46);g(40);let k;const t=()=>{k||(k=new l.Router,k.addFetchListener(),k.addCacheListener());return k}};
shadow$provide[48]=function(n,g,C,p){function l(x,E,P){if("string"===typeof x){const B=new URL(x,location.href);x=new t.Route(({url:K})=>K.href===B.href,E,P)}else if(x instanceof RegExp)x=new v.RegExpRoute(x,E,P);else if("function"===typeof x)x=new t.Route(x,E,P);else if(!(x instanceof t.Route))throw new k.WorkboxError("unsupported-route-type",{moduleName:"workbox-routing",funcName:"registerRoute",paramName:"capture"});(0,q.getOrCreateDefaultRouter)().registerRoute(x);return x}Object.defineProperties(p,
{__esModule:{enumerable:!0,value:!0},registerRoute:{enumerable:!0,get:function(){return l}}});g(14);var k=g(17),t=g(43),v=g(45),q=g(47);g(40)};
shadow$provide[49]=function(n,g,C,p){function l(t){(0,k.getOrCreateDefaultRouter)().setCatchHandler(t)}Object.defineProperties(p,{__esModule:{enumerable:!0,value:!0},setCatchHandler:{enumerable:!0,get:function(){return l}}});var k=g(47);g(40)};
shadow$provide[50]=function(n,g,C,p){function l(t){(0,k.getOrCreateDefaultRouter)().setDefaultHandler(t)}Object.defineProperties(p,{__esModule:{enumerable:!0,value:!0},setDefaultHandler:{enumerable:!0,get:function(){return l}}});var k=g(47);g(40)};
shadow$provide[51]=function(n,g,C,p){Object.defineProperties(p,{__esModule:{enumerable:!0,value:!0},NavigationRoute:{enumerable:!0,get:function(){return l.NavigationRoute}},RegExpRoute:{enumerable:!0,get:function(){return k.RegExpRoute}},Route:{enumerable:!0,get:function(){return v.Route}},Router:{enumerable:!0,get:function(){return q.Router}},registerRoute:{enumerable:!0,get:function(){return t.registerRoute}},setCatchHandler:{enumerable:!0,get:function(){return x.setCatchHandler}},setDefaultHandler:{enumerable:!0,
get:function(){return E.setDefaultHandler}}});var l=g(44),k=g(45),t=g(48),v=g(43),q=g(46),x=g(49),E=g(50);g(40)};
shadow$provide[52]=function(n,g,C,p){try{self["workbox:precaching:7.0.0"]&&_()}catch(l){}};
shadow$provide[53]=function(n,g,C,p){function l(t){if(!t)throw new k.WorkboxError("add-to-cache-list-unexpected-type",{entry:t});if("string"===typeof t)return t=new URL(t,location.href),{cacheKey:t.href,url:t.href};const {revision:v,url:q}=t;if(!q)throw new k.WorkboxError("add-to-cache-list-unexpected-type",{entry:t});if(!v)return t=new URL(q,location.href),{cacheKey:t.href,url:t.href};t=new URL(q,location.href);const x=new URL(q,location.href);t.searchParams.set("__WB_REVISION__",v);return{cacheKey:t.href,
url:x.href}}Object.defineProperties(p,{__esModule:{enumerable:!0,value:!0},createCacheKey:{enumerable:!0,get:function(){return l}}});var k=g(17);g(52)};
shadow$provide[54]=function(n,g,C,p){Object.defineProperties(p,{__esModule:{enumerable:!0,value:!0},PrecacheInstallReportPlugin:{enumerable:!0,get:function(){return l}}});g(52);class l{constructor(){this.updatedURLs=[];this.notUpdatedURLs=[];this.handlerWillStart=async({request:k,state:t})=>{t&&(t.originalRequest=k)};this.cachedResponseWillBeUsed=async({event:k,state:t,cachedResponse:v})=>{"install"===k.type&&t&&t.originalRequest&&t.originalRequest instanceof Request&&(k=t.originalRequest.url,v?this.notUpdatedURLs.push(k):
this.updatedURLs.push(k));return v}}}};
shadow$provide[55]=function(n,g,C,p){Object.defineProperties(p,{__esModule:{enumerable:!0,value:!0},PrecacheCacheKeyPlugin:{enumerable:!0,get:function(){return l}}});g(52);class l{constructor({precacheController:k}){this.cacheKeyWillBeUsed=async({request:t,params:v})=>(v=(null===v||void 0===v?void 0:v.cacheKey)||this._precacheController.getCacheKeyForURL(t.url))?new Request(v,{headers:t.headers}):t;this._precacheController=k}}};
shadow$provide[56]=function(n,g,C,p){function l(t){const v=t.length;if(0<v){k.logger.groupCollapsed("During precaching cleanup, "+`${v} cached `+`request${1===v?" was":"s were"} deleted.`);k.logger.groupCollapsed("Deleted Cache Requests");for(const q of t)k.logger.log(q);k.logger.groupEnd();k.logger.groupEnd()}}Object.defineProperties(p,{__esModule:{enumerable:!0,value:!0},printCleanupDetails:{enumerable:!0,get:function(){return l}}});var k=g(14);g(52)};
shadow$provide[57]=function(n,g,C,p){function l(v,q){if(0!==q.length){t.logger.groupCollapsed(v);for(const x of q)t.logger.log(x);t.logger.groupEnd()}}function k(v,q){var x=v.length;const E=q.length;if(x||E)x=`Precaching ${x} file${1===x?"":"s"}.`,0<E&&(x+=` ${E} `+`file${1===E?" is":"s are"} already cached.`),t.logger.groupCollapsed(x),l("View newly precached URLs.",v),l("View previously precached URLs.",q),t.logger.groupEnd()}Object.defineProperties(p,{__esModule:{enumerable:!0,value:!0},printInstallDetails:{enumerable:!0,
get:function(){return k}}});var t=g(14);g(52)};
shadow$provide[58]=function(n,g,C,p){try{self["workbox:strategies:7.0.0"]&&_()}catch(l){}};
shadow$provide[59]=function(n,g,C,p){function l(B){return"string"===typeof B?new Request(B):B}Object.defineProperties(p,{__esModule:{enumerable:!0,value:!0},StrategyHandler:{enumerable:!0,get:function(){return P}}});g(18);var k=g(22),t=g(26),v=g(27),q=g(28);g(14);var x=g(29),E=g(17);g(58);class P{constructor(B,K){this._cacheKeys={};Object.assign(this,K);this.event=K.event;this._strategy=B;this._handlerDeferred=new t.Deferred;this._extendLifetimePromises=[];this._plugins=[...B.plugins];this._pluginStateMap=
new Map;for(const N of this._plugins)this._pluginStateMap.set(N,{});this.event.waitUntil(this._handlerDeferred.promise)}async fetch(B){const {event:K}=this;B=l(B);if("navigate"===B.mode&&K instanceof FetchEvent&&K.preloadResponse){var N=await K.preloadResponse;if(N)return N}N=this.hasCallback("fetchDidFail")?B.clone():null;try{for(var ea of this.iterateCallbacks("requestWillFetch"))B=await ea({request:B.clone(),event:K})}catch(fa){if(fa instanceof Error)throw new E.WorkboxError("plugin-error-request-will-fetch",
{thrownErrorMessage:fa.message});}ea=B.clone();try{let fa;fa=await fetch(B,"navigate"===B.mode?void 0:this._strategy.fetchOptions);for(const Q of this.iterateCallbacks("fetchDidSucceed"))fa=await Q({event:K,request:ea,response:fa});return fa}catch(fa){throw N&&await this.runCallbacks("fetchDidFail",{error:fa,event:K,originalRequest:N.clone(),request:ea.clone()}),fa;}}async fetchAndCachePut(B){const K=await this.fetch(B),N=K.clone();void this.waitUntil(this.cachePut(B,N));return K}async cacheMatch(B){B=
l(B);const {cacheName:K,matchOptions:N}=this._strategy;B=await this.getCacheKey(B,"read");var ea=Object.assign(Object.assign({},N),{cacheName:K});ea=await caches.match(B,ea);for(const fa of this.iterateCallbacks("cachedResponseWillBeUsed"))ea=await fa({cacheName:K,matchOptions:N,cachedResponse:ea,request:B,event:this.event})||void 0;return ea}async cachePut(B,K){B=l(B);await (0,x.timeout)(0);B=await this.getCacheKey(B,"write");if(!K)throw new E.WorkboxError("cache-put-with-no-response",{url:(0,q.getFriendlyURL)(B.url)});
K=await this._ensureResponseSafeToCache(K);if(!K)return!1;const {cacheName:N,matchOptions:ea}=this._strategy,fa=await self.caches.open(N),Q=this.hasCallback("cacheDidUpdate"),W=Q?await (0,k.cacheMatchIgnoreParams)(fa,B.clone(),["__WB_REVISION__"],ea):null;try{await fa.put(B,Q?K.clone():K)}catch(T){if(T instanceof Error)throw"QuotaExceededError"===T.name&&await (0,v.executeQuotaErrorCallbacks)(),T;}for(const T of this.iterateCallbacks("cacheDidUpdate"))await T({cacheName:N,oldResponse:W,newResponse:K.clone(),
request:B,event:this.event});return!0}async getCacheKey(B,K){const N=`${B.url} | ${K}`;if(!this._cacheKeys[N]){for(const ea of this.iterateCallbacks("cacheKeyWillBeUsed"))B=l(await ea({mode:K,request:B,event:this.event,params:this.params}));this._cacheKeys[N]=B}return this._cacheKeys[N]}hasCallback(B){for(const K of this._strategy.plugins)if(B in K)return!0;return!1}async runCallbacks(B,K){for(const N of this.iterateCallbacks(B))await N(K)}*iterateCallbacks(B){for(const K of this._strategy.plugins)if("function"===
typeof K[B]){const N=this._pluginStateMap.get(K);yield(ea=>{ea=Object.assign(Object.assign({},ea),{state:N});return K[B](ea)})}}waitUntil(B){this._extendLifetimePromises.push(B);return B}async doneWaiting(){let B;for(;B=this._extendLifetimePromises.shift();)await B}destroy(){this._handlerDeferred.resolve(null)}async _ensureResponseSafeToCache(B){let K=!1;for(const N of this.iterateCallbacks("cacheWillUpdate"))if(B=await N({request:this.request,response:B,event:this.event})||void 0,K=!0,!B)break;K||
B&&200!==B.status&&(B=void 0);return B}}};
shadow$provide[60]=function(n,g,C,p){Object.defineProperties(p,{__esModule:{enumerable:!0,value:!0},Strategy:{enumerable:!0,get:function(){return v}}});var l=g(21),k=g(17);g(14);g(28);var t=g(59);g(58);class v{constructor(q={}){this.cacheName=l.cacheNames.getRuntimeName(q.cacheName);this.plugins=q.plugins||[];this.fetchOptions=q.fetchOptions;this.matchOptions=q.matchOptions}handle(q){[q]=this.handleAll(q);return q}handleAll(q){q instanceof FetchEvent&&(q={event:q,request:q.request});var x=q.event;
const E="string"===typeof q.request?new Request(q.request):q.request,P=new t.StrategyHandler(this,{event:x,request:E,params:"params"in q?q.params:void 0});q=this._getResponse(P,E,x);x=this._awaitComplete(q,P,E,x);return[q,x]}async _getResponse(q,x,E){await q.runCallbacks("handlerWillStart",{event:E,request:x});let P=void 0;try{if(P=await this._handle(x,q),!P||"error"===P.type)throw new k.WorkboxError("no-response",{url:x.url});}catch(B){if(B instanceof Error)for(const K of q.iterateCallbacks("handlerDidError"))if(P=
await K({error:B,event:E,request:x}))break;if(!P)throw B;}for(const B of q.iterateCallbacks("handlerWillRespond"))P=await B({event:E,request:x,response:P});return P}async _awaitComplete(q,x,E,P){let B,K;try{B=await q}catch(N){}try{await x.runCallbacks("handlerDidRespond",{event:P,request:E,response:B}),await x.doneWaiting()}catch(N){N instanceof Error&&(K=N)}await x.runCallbacks("handlerDidComplete",{event:P,request:E,response:B,error:K});x.destroy();if(K)throw K;}}};
shadow$provide[61]=function(n,g,C,p){Object.defineProperties(p,{__esModule:{enumerable:!0,value:!0},PrecacheStrategy:{enumerable:!0,get:function(){return v}}});var l=g(34),k=g(21);g(28);g(14);var t=g(17);n=g(60);g(52);class v extends n.Strategy{constructor(q={}){q.cacheName=k.cacheNames.getPrecacheName(q.cacheName);super(q);this._fallbackToNetwork=!1===q.fallbackToNetwork?!1:!0;this.plugins.push(v.copyRedirectedCacheableResponsesPlugin)}async _handle(q,x){const E=await x.cacheMatch(q);return E?E:
x.event&&"install"===x.event.type?await this._handleInstall(q,x):await this._handleFetch(q,x)}async _handleFetch(q,x){var E=x.params||{};if(this._fallbackToNetwork){E=E.integrity;var P=q.integrity;const B=!P||P===E;P=await x.fetch(new Request(q,{integrity:"no-cors"!==q.mode?P||E:void 0}));E&&B&&"no-cors"!==q.mode&&(this._useDefaultCacheabilityPluginIfNeeded(),await x.cachePut(q,P.clone()))}else throw new t.WorkboxError("missing-precache-entry",{cacheName:this.cacheName,url:q.url});return P}async _handleInstall(q,
x){this._useDefaultCacheabilityPluginIfNeeded();const E=await x.fetch(q);if(!await x.cachePut(q,E.clone()))throw new t.WorkboxError("bad-precaching-response",{url:q.url,status:E.status});return E}_useDefaultCacheabilityPluginIfNeeded(){let q=null,x=0;for(const [E,P]of this.plugins.entries())P!==v.copyRedirectedCacheableResponsesPlugin&&(P===v.defaultPrecacheCacheabilityPlugin&&(q=E),P.cacheWillUpdate&&x++);0===x?this.plugins.push(v.defaultPrecacheCacheabilityPlugin):1<x&&null!==q&&this.plugins.splice(q,
1)}}v.defaultPrecacheCacheabilityPlugin={async cacheWillUpdate({response:q}){return!q||400<=q.status?null:q}};v.copyRedirectedCacheableResponsesPlugin={async cacheWillUpdate({response:q}){return q.redirected?await (0,l.copyResponse)(q):q}}};
shadow$provide[62]=function(n,g,C,p){Object.defineProperties(p,{__esModule:{enumerable:!0,value:!0},PrecacheController:{enumerable:!0,get:function(){return P}}});g(18);var l=g(21);g(14);var k=g(17),t=g(31),v=g(53),q=g(54),x=g(55);g(56);g(57);var E=g(61);g(52);class P{constructor({cacheName:B,plugins:K=[],fallbackToNetwork:N=!0}={}){this._urlsToCacheKeys=new Map;this._urlsToCacheModes=new Map;this._cacheKeysToIntegrities=new Map;this._strategy=new E.PrecacheStrategy({cacheName:l.cacheNames.getPrecacheName(B),
plugins:[...K,new x.PrecacheCacheKeyPlugin({precacheController:this})],fallbackToNetwork:N});this.install=this.install.bind(this);this.activate=this.activate.bind(this)}get strategy(){return this._strategy}precache(B){this.addToCacheList(B);this._installAndActiveListenersAdded||(self.addEventListener("install",this.install),self.addEventListener("activate",this.activate),this._installAndActiveListenersAdded=!0)}addToCacheList(B){const K=[];for(const N of B){"string"===typeof N?K.push(N):N&&void 0===
N.revision&&K.push(N.url);const {cacheKey:ea,url:fa}=(0,v.createCacheKey)(N);B="string"!==typeof N&&N.revision?"reload":"default";if(this._urlsToCacheKeys.has(fa)&&this._urlsToCacheKeys.get(fa)!==ea)throw new k.WorkboxError("add-to-cache-list-conflicting-entries",{firstEntry:this._urlsToCacheKeys.get(fa),secondEntry:ea});if("string"!==typeof N&&N.integrity){if(this._cacheKeysToIntegrities.has(ea)&&this._cacheKeysToIntegrities.get(ea)!==N.integrity)throw new k.WorkboxError("add-to-cache-list-conflicting-integrities",
{url:fa});this._cacheKeysToIntegrities.set(ea,N.integrity)}this._urlsToCacheKeys.set(fa,ea);this._urlsToCacheModes.set(fa,B);0<K.length&&(B="Workbox is precaching URLs without revision "+`info: ${K.join(", ")}\nThis is generally NOT safe. `+"Learn more at https://bit.ly/wb-precache",console.warn(B))}}install(B){return(0,t.waitUntil)(B,async()=>{const K=new q.PrecacheInstallReportPlugin;this.strategy.plugins.push(K);for(const [Q,W]of this._urlsToCacheKeys){var N=this._cacheKeysToIntegrities.get(W);
const T=this._urlsToCacheModes.get(Q);N=new Request(Q,{integrity:N,cache:T,credentials:"same-origin"});await Promise.all(this.strategy.handleAll({params:{cacheKey:W},request:N,event:B}))}const {updatedURLs:ea,notUpdatedURLs:fa}=K;return{updatedURLs:ea,notUpdatedURLs:fa}})}activate(B){return(0,t.waitUntil)(B,async()=>{const K=await self.caches.open(this.strategy.cacheName),N=await K.keys(),ea=new Set(this._urlsToCacheKeys.values()),fa=[];for(const Q of N)ea.has(Q.url)||(await K.delete(Q),fa.push(Q.url));
return{deletedURLs:fa}})}getURLsToCacheKeys(){return this._urlsToCacheKeys}getCachedURLs(){return[...this._urlsToCacheKeys.keys()]}getCacheKeyForURL(B){B=new URL(B,location.href);return this._urlsToCacheKeys.get(B.href)}getIntegrityForCacheKey(B){return this._cacheKeysToIntegrities.get(B)}async matchPrecache(B){if(B=this.getCacheKeyForURL(B instanceof Request?B.url:B))return(await self.caches.open(this.strategy.cacheName)).match(B)}createHandlerBoundToURL(B){const K=this.getCacheKeyForURL(B);if(!K)throw new k.WorkboxError("non-precached-url",
{url:B});return N=>{N.request=new Request(B);N.params=Object.assign({cacheKey:K},N.params);return this.strategy.handle(N)}}}};
shadow$provide[63]=function(n,g,C,p){Object.defineProperties(p,{__esModule:{enumerable:!0,value:!0},getOrCreatePrecacheController:{enumerable:!0,get:function(){return t}}});var l=g(62);g(52);let k;const t=()=>{k||(k=new l.PrecacheController);return k}};
shadow$provide[64]=function(n,g,C,p){function l(t){(0,k.getOrCreatePrecacheController)().strategy.plugins.push(...t)}Object.defineProperties(p,{__esModule:{enumerable:!0,value:!0},addPlugins:{enumerable:!0,get:function(){return l}}});var k=g(63);g(52)};
shadow$provide[65]=function(n,g,C,p){function l(k,t=[]){for(const v of[...k.searchParams.keys()])t.some(q=>q.test(v))&&k.searchParams.delete(v);return k}Object.defineProperties(p,{__esModule:{enumerable:!0,value:!0},removeIgnoredSearchParams:{enumerable:!0,get:function(){return l}}});g(52)};
shadow$provide[66]=function(n,g,C,p){function*l(t,{ignoreURLParametersMatching:v=[/^utm_/,/^fbclid$/],directoryIndex:q="index.html",cleanURLs:x=!0,urlManipulation:E}={}){t=new URL(t,location.href);t.hash="";yield t.href;v=(0,k.removeIgnoredSearchParams)(t,v);yield v.href;if(q&&v.pathname.endsWith("/")){const P=new URL(v.href);P.pathname+=q;yield P.href}x&&(q=new URL(v.href),q.pathname+=".html",yield q.href);if(E){E=E({url:t});for(const P of E)yield P.href}}Object.defineProperties(p,{__esModule:{enumerable:!0,
value:!0},generateURLVariations:{enumerable:!0,get:function(){return l}}});var k=g(65);g(52)};
shadow$provide[67]=function(n,g,C,p){Object.defineProperties(p,{__esModule:{enumerable:!0,value:!0},PrecacheRoute:{enumerable:!0,get:function(){return k}}});g(14);g(28);n=g(43);var l=g(66);g(52);class k extends n.Route{constructor(t,v){super(({request:q})=>{var x=t.getURLsToCacheKeys();for(const E of(0,l.generateURLVariations)(q.url,v))if(q=x.get(E))return x=t.getIntegrityForCacheKey(q),{cacheKey:q,integrity:x}},t.strategy)}}};
shadow$provide[68]=function(n,g,C,p){function l(q){const x=(0,t.getOrCreatePrecacheController)();q=new v.PrecacheRoute(x,q);(0,k.registerRoute)(q)}Object.defineProperties(p,{__esModule:{enumerable:!0,value:!0},addRoute:{enumerable:!0,get:function(){return l}}});var k=g(48),t=g(63),v=g(67);g(52)};
shadow$provide[69]=function(n,g,C,p){Object.defineProperties(p,{__esModule:{enumerable:!0,value:!0},deleteOutdatedCaches:{enumerable:!0,get:function(){return l}}});g(52);const l=async(k,t="-precache-")=>{const v=(await self.caches.keys()).filter(q=>q.includes(t)&&q.includes(self.registration.scope)&&q!==k);await Promise.all(v.map(q=>self.caches.delete(q)));return v}};
shadow$provide[70]=function(n,g,C,p){function l(){self.addEventListener("activate",v=>{const q=k.cacheNames.getPrecacheName();v.waitUntil((0,t.deleteOutdatedCaches)(q).then(x=>{}))})}Object.defineProperties(p,{__esModule:{enumerable:!0,value:!0},cleanupOutdatedCaches:{enumerable:!0,get:function(){return l}}});var k=g(21);g(14);var t=g(69);g(52)};
shadow$provide[71]=function(n,g,C,p){function l(t){return(0,k.getOrCreatePrecacheController)().createHandlerBoundToURL(t)}Object.defineProperties(p,{__esModule:{enumerable:!0,value:!0},createHandlerBoundToURL:{enumerable:!0,get:function(){return l}}});var k=g(63);g(52)};
shadow$provide[72]=function(n,g,C,p){function l(t){return(0,k.getOrCreatePrecacheController)().getCacheKeyForURL(t)}Object.defineProperties(p,{__esModule:{enumerable:!0,value:!0},getCacheKeyForURL:{enumerable:!0,get:function(){return l}}});var k=g(63);g(52)};
shadow$provide[73]=function(n,g,C,p){function l(t){return(0,k.getOrCreatePrecacheController)().matchPrecache(t)}Object.defineProperties(p,{__esModule:{enumerable:!0,value:!0},matchPrecache:{enumerable:!0,get:function(){return l}}});var k=g(63);g(52)};
shadow$provide[74]=function(n,g,C,p){function l(t){(0,k.getOrCreatePrecacheController)().precache(t)}Object.defineProperties(p,{__esModule:{enumerable:!0,value:!0},precache:{enumerable:!0,get:function(){return l}}});var k=g(63);g(52)};
shadow$provide[75]=function(n,g,C,p){function l(v,q){(0,t.precache)(v);(0,k.addRoute)(q)}Object.defineProperties(p,{__esModule:{enumerable:!0,value:!0},precacheAndRoute:{enumerable:!0,get:function(){return l}}});var k=g(68),t=g(74);g(52)};
shadow$provide[76]=function(n,g,C,p){Object.defineProperties(p,{__esModule:{enumerable:!0,value:!0},PrecacheFallbackPlugin:{enumerable:!0,get:function(){return k}}});var l=g(63);g(52);class k{constructor({fallbackURL:t,precacheController:v}){this.handlerDidError=()=>this._precacheController.matchPrecache(this._fallbackURL);this._fallbackURL=t;this._precacheController=v||(0,l.getOrCreatePrecacheController)()}}};
shadow$provide[77]=function(n,g,C,p){g(52)};
shadow$provide[78]=function(n,g,C,p){Object.defineProperties(p,{__esModule:{enumerable:!0,value:!0},PrecacheController:{enumerable:!0,get:function(){return B.PrecacheController}},PrecacheFallbackPlugin:{enumerable:!0,get:function(){return ea.PrecacheFallbackPlugin}},PrecacheRoute:{enumerable:!0,get:function(){return K.PrecacheRoute}},PrecacheStrategy:{enumerable:!0,get:function(){return N.PrecacheStrategy}},addPlugins:{enumerable:!0,get:function(){return l.addPlugins}},addRoute:{enumerable:!0,get:function(){return k.addRoute}},
cleanupOutdatedCaches:{enumerable:!0,get:function(){return t.cleanupOutdatedCaches}},createHandlerBoundToURL:{enumerable:!0,get:function(){return v.createHandlerBoundToURL}},getCacheKeyForURL:{enumerable:!0,get:function(){return q.getCacheKeyForURL}},matchPrecache:{enumerable:!0,get:function(){return x.matchPrecache}},precache:{enumerable:!0,get:function(){return E.precache}},precacheAndRoute:{enumerable:!0,get:function(){return P.precacheAndRoute}}});var l=g(64),k=g(68),t=g(70),v=g(71),q=g(72),x=
g(73),E=g(74),P=g(75),B=g(62),K=g(67),N=g(61),ea=g(76);g(52);n=g(77);g.exportCopy(C,n)};
shadow$provide[79]=function(n,g,C,p){Object.defineProperties(p,{__esModule:{enumerable:!0,value:!0},messages:{enumerable:!0,get:function(){return t}}});var l=g(14),k=g(28);g(58);const t={strategyStart:(v,q)=>`Using ${v} to respond to '${(0,k.getFriendlyURL)(q.url)}'`,printFinalResponse:v=>{v&&(l.logger.groupCollapsed("View the final response here."),l.logger.log(v||"[No response returned]"),l.logger.groupEnd())}}};
shadow$provide[80]=function(n,g,C,p){Object.defineProperties(p,{__esModule:{enumerable:!0,value:!0},CacheFirst:{enumerable:!0,get:function(){return k}}});g(18);g(14);var l=g(17);n=g(60);g(79);g(58);class k extends n.Strategy{async _handle(t,v){let q=await v.cacheMatch(t),x=void 0;if(!q)try{q=await v.fetchAndCachePut(t)}catch(E){E instanceof Error&&(x=E)}if(!q)throw new l.WorkboxError("no-response",{url:t.url,error:x});return q}}};
shadow$provide[81]=function(n,g,C,p){Object.defineProperties(p,{__esModule:{enumerable:!0,value:!0},CacheOnly:{enumerable:!0,get:function(){return k}}});g(18);g(14);var l=g(17);n=g(60);g(79);g(58);class k extends n.Strategy{async _handle(t,v){v=await v.cacheMatch(t);if(!v)throw new l.WorkboxError("no-response",{url:t.url});return v}}};
shadow$provide[82]=function(n,g,C,p){Object.defineProperties(p,{__esModule:{enumerable:!0,value:!0},cacheOkAndOpaquePlugin:{enumerable:!0,get:function(){return l}}});g(58);const l={cacheWillUpdate:async({response:k})=>200===k.status||0===k.status?k:null}};
shadow$provide[83]=function(n,g,C,p){Object.defineProperties(p,{__esModule:{enumerable:!0,value:!0},NetworkFirst:{enumerable:!0,get:function(){return t}}});g(18);g(14);var l=g(17),k=g(82);n=g(60);g(79);g(58);class t extends n.Strategy{constructor(v={}){super(v);this.plugins.some(q=>"cacheWillUpdate"in q)||this.plugins.unshift(k.cacheOkAndOpaquePlugin);this._networkTimeoutSeconds=v.networkTimeoutSeconds||0}async _handle(v,q){var x=[];const E=[];let P;if(this._networkTimeoutSeconds){const {id:K,promise:N}=
this._getTimeoutPromise({request:v,logs:x,handler:q});P=K;E.push(N)}const B=this._getNetworkPromise({timeoutId:P,request:v,logs:x,handler:q});E.push(B);x=await q.waitUntil((async()=>await q.waitUntil(Promise.race(E))||await B)());if(!x)throw new l.WorkboxError("no-response",{url:v.url});return x}_getTimeoutPromise({request:v,handler:q}){let x;return{promise:new Promise(E=>{x=setTimeout(async()=>{E(await q.cacheMatch(v))},1E3*this._networkTimeoutSeconds)}),id:x}}async _getNetworkPromise({timeoutId:v,
request:q,handler:x}){let E,P;try{P=await x.fetchAndCachePut(q)}catch(B){B instanceof Error&&(E=B)}v&&clearTimeout(v);if(E||!P)P=await x.cacheMatch(q);return P}}};
shadow$provide[84]=function(n,g,C,p){Object.defineProperties(p,{__esModule:{enumerable:!0,value:!0},NetworkOnly:{enumerable:!0,get:function(){return t}}});g(18);g(14);var l=g(29),k=g(17);n=g(60);g(79);g(58);class t extends n.Strategy{constructor(v={}){super(v);this._networkTimeoutSeconds=v.networkTimeoutSeconds||0}async _handle(v,q){let x=void 0,E;try{const P=[q.fetch(v)];if(this._networkTimeoutSeconds){const B=(0,l.timeout)(1E3*this._networkTimeoutSeconds);P.push(B)}E=await Promise.race(P);if(!E)throw Error("Timed out the network response after "+
`${this._networkTimeoutSeconds} seconds.`);}catch(P){P instanceof Error&&(x=P)}if(!E)throw new k.WorkboxError("no-response",{url:v.url,error:x});return E}}};
shadow$provide[85]=function(n,g,C,p){Object.defineProperties(p,{__esModule:{enumerable:!0,value:!0},StaleWhileRevalidate:{enumerable:!0,get:function(){return t}}});g(18);g(14);var l=g(17),k=g(82);n=g(60);g(79);g(58);class t extends n.Strategy{constructor(v={}){super(v);this.plugins.some(q=>"cacheWillUpdate"in q)||this.plugins.unshift(k.cacheOkAndOpaquePlugin)}async _handle(v,q){const x=q.fetchAndCachePut(v).catch(()=>{});void q.waitUntil(x);q=await q.cacheMatch(v);let E;if(!q)try{q=await x}catch(P){P instanceof
Error&&(E=P)}if(!q)throw new l.WorkboxError("no-response",{url:v.url,error:E});return q}}};
shadow$provide[86]=function(n,g,C,p){Object.defineProperties(p,{__esModule:{enumerable:!0,value:!0},CacheFirst:{enumerable:!0,get:function(){return l.CacheFirst}},CacheOnly:{enumerable:!0,get:function(){return k.CacheOnly}},NetworkFirst:{enumerable:!0,get:function(){return t.NetworkFirst}},NetworkOnly:{enumerable:!0,get:function(){return v.NetworkOnly}},StaleWhileRevalidate:{enumerable:!0,get:function(){return q.StaleWhileRevalidate}},Strategy:{enumerable:!0,get:function(){return x.Strategy}},StrategyHandler:{enumerable:!0,
get:function(){return E.StrategyHandler}}});var l=g(80),k=g(81),t=g(83),v=g(84),q=g(85),x=g(60),E=g(59);g(58)};
'use strict';$APP.kg(12,{});var sN=$APP.kg(39,{});var tN=$APP.kg(51,{});var uN=$APP.kg(78,{});var vN=$APP.kg(86,{});var V0=$APP.Ig($APP.Rf.ha(function(a){return["/wiki-guides",$APP.r.Ea(a)].join("")},new $APP.S(null,15,5,$APP.T,"/index.html /assets/re-com/css/bootstrap.css /assets/re-com/css/material-design-iconic-font.min.css /assets/re-com/css/re-com.css /assets/re-com/css/chosen-sprite.png /assets/re-com/css/chosen-sprite@2x.png /assets/re-com/fonts/Material-Design-Iconic-Font.eot /assets/re-com/fonts/Material-Design-Iconic-Font.svg /assets/re-com/fonts/Material-Design-Iconic-Font.ttf /assets/re-com/fonts/Material-Design-Iconic-Font.woff /assets/re-com/fonts/Material-Design-Iconic-Font.woff2 /assets/re-com/scripts/detect-element-resize.js /assets/css/app.css /shared.js /app.js".split(" "),
null)));self.addEventListener("install",function(a){return a.waitUntil(caches.open(sN.cacheNames.runtime).then(function(b){return b.addAll(V0)}))});self.addEventListener("message",function(a){a=null==a?null:a.data;return $APP.I.ha(null==a?null:a.type,"SKIP_WAITING")?self.skipWaiting():null});tN.registerRoute(function(a){return $APP.I.ha(a.request.destination,"image")},new vN.CacheFirst);tN.setDefaultHandler(new vN.StaleWhileRevalidate);uN.precacheAndRoute([{url:"/wiki-guides/index.html",revision:"e4bc9d0fe6083709a028348e8d044ae022767b67b75c6dcbe921ba448242410c"}]);
tN.registerRoute(new tN.NavigationRoute(uN.createHandlerBoundToURL("/wiki-guides/index.html")));
}).call(this);