importScripts("shared.js");
(function(){
shadow$provide[10]=function(F,h,K,r){F=function(m){function l(E,G,k){Object.defineProperty(E,G,{value:k,enumerable:!0,configurable:!0,writable:!0});return E[G]}function q(E,G,k,y){G=Object.create((G&&G.prototype instanceof n?G:n).prototype);y=new ja(y||[]);xa(G,"_invoke",{value:L(E,k,y)});return G}function u(E,G,k){try{return{type:"normal",arg:E.call(G,k)}}catch(y){return{type:"throw",arg:y}}}function n(){}function w(){}function D(){}function N(E){["next","throw","return"].forEach(function(G){l(E,
G,function(k){return this._invoke(G,k)})})}function A(E,G){function k(C,Q,R,ba){C=u(E[C],E,Q);if("throw"===C.type)ba(C.arg);else{var ca=C.arg;return(C=ca.value)&&"object"===typeof C&&Va.call(C,"__await")?G.resolve(C.__await).then(function(da){k("next",da,R,ba)},function(da){k("throw",da,R,ba)}):G.resolve(C).then(function(da){ca.value=da;R(ca)},function(da){return k("throw",da,R,ba)})}}var y;xa(this,"_invoke",{value:function(C,Q){function R(){return new G(function(ba,ca){k(C,Q,ba,ca)})}return y=y?
y.then(R,R):R()}})}function L(E,G,k){var y=ob;return function(C,Q){if(y===bb)throw Error("Generator is already running");if(y===Ma){if("throw"===C)throw Q;return{value:ea,done:!0}}k.method=C;for(k.arg=Q;;){if(C=k.delegate)if(C=O(C,k)){if(C===ma)continue;return C}if("next"===k.method)k.sent=k._sent=k.arg;else if("throw"===k.method){if(y===ob)throw y=Ma,k.arg;k.dispatchException(k.arg)}else"return"===k.method&&k.abrupt("return",k.arg);y=bb;C=u(E,G,k);if("normal"===C.type){y=k.done?Ma:Wa;if(C.arg===
ma)continue;return{value:C.arg,done:k.done}}"throw"===C.type&&(y=Ma,k.method="throw",k.arg=C.arg)}}}function O(E,G){var k=G.method,y=E.iterator[k];if(y===ea){G.delegate=null;if("throw"===k&&E.iterator["return"]&&(G.method="return",G.arg=ea,O(E,G),"throw"===G.method))return ma;"return"!==k&&(G.method="throw",G.arg=new TypeError("The iterator does not provide a '"+k+"' method"));return ma}k=u(y,E.iterator,G.arg);if("throw"===k.type)return G.method="throw",G.arg=k.arg,G.delegate=null,ma;k=k.arg;if(!k)return G.method=
"throw",G.arg=new TypeError("iterator result is not an object"),G.delegate=null,ma;if(k.done)G[E.resultName]=k.value,G.next=E.nextLoc,"return"!==G.method&&(G.method="next",G.arg=ea);else return k;G.delegate=null;return ma}function Y(E){var G={tryLoc:E[0]};1 in E&&(G.catchLoc=E[1]);2 in E&&(G.finallyLoc=E[2],G.afterLoc=E[3]);this.tryEntries.push(G)}function Z(E){var G=E.completion||{};G.type="normal";delete G.arg;E.completion=G}function ja(E){this.tryEntries=[{tryLoc:"root"}];E.forEach(Y,this);this.reset(!0)}
function oa(E){if(null!=E){var G=E[za];if(G)return G.call(E);if("function"===typeof E.next)return E;if(!isNaN(E.length)){var k=-1;G=function C(){for(;++k<E.length;)if(Va.call(E,k))return C.value=E[k],C.done=!1,C;C.value=ea;C.done=!0;return C};return G.next=G}}throw new TypeError(typeof E+" is not iterable");}var ka=Object.prototype,Va=ka.hasOwnProperty,xa=Object.defineProperty||function(E,G,k){E[G]=k.value},ea,Ia="function"===typeof Symbol?Symbol:{},za=Ia.iterator||"@@iterator",Ua=Ia.asyncIterator||
"@@asyncIterator",hb=Ia.toStringTag||"@@toStringTag";try{l({},"")}catch(E){l=function(G,k,y){return G[k]=y}}m.wrap=q;var ob="suspendedStart",Wa="suspendedYield",bb="executing",Ma="completed",ma={};Ia={};l(Ia,za,function(){return this});var Ha=Object.getPrototypeOf;(Ha=Ha&&Ha(Ha(oa([]))))&&Ha!==ka&&Va.call(Ha,za)&&(Ia=Ha);var Sa=D.prototype=n.prototype=Object.create(Ia);w.prototype=D;xa(Sa,"constructor",{value:D,configurable:!0});xa(D,"constructor",{value:w,configurable:!0});w.displayName=l(D,hb,"GeneratorFunction");
m.isGeneratorFunction=function(E){return(E="function"===typeof E&&E.constructor)?E===w||"GeneratorFunction"===(E.displayName||E.name):!1};m.mark=function(E){Object.setPrototypeOf?Object.setPrototypeOf(E,D):(E.__proto__=D,l(E,hb,"GeneratorFunction"));E.prototype=Object.create(Sa);return E};m.awrap=function(E){return{__await:E}};N(A.prototype);l(A.prototype,Ua,function(){return this});m.AsyncIterator=A;m.async=function(E,G,k,y,C){void 0===C&&(C=Promise);var Q=new A(q(E,G,k,y),C);return m.isGeneratorFunction(G)?
Q:Q.next().then(function(R){return R.done?R.value:Q.next()})};N(Sa);l(Sa,hb,"Generator");l(Sa,za,function(){return this});l(Sa,"toString",function(){return"[object Generator]"});m.keys=function(E){var G=Object(E),k=[],y;for(y in G)k.push(y);k.reverse();return function Q(){for(;k.length;){var R=k.pop();if(R in G)return Q.value=R,Q.done=!1,Q}Q.done=!0;return Q}};m.values=oa;ja.prototype={constructor:ja,reset:function(E){this.next=this.prev=0;this.sent=this._sent=ea;this.done=!1;this.delegate=null;this.method=
"next";this.arg=ea;this.tryEntries.forEach(Z);if(!E)for(var G in this)"t"===G.charAt(0)&&Va.call(this,G)&&!isNaN(+G.slice(1))&&(this[G]=ea)},stop:function(){this.done=!0;var E=this.tryEntries[0].completion;if("throw"===E.type)throw E.arg;return this.rval},dispatchException:function(E){function G(ca,da){Q.type="throw";Q.arg=E;k.next=ca;da&&(k.method="next",k.arg=ea);return!!da}if(this.done)throw E;for(var k=this,y=this.tryEntries.length-1;0<=y;--y){var C=this.tryEntries[y],Q=C.completion;if("root"===
C.tryLoc)return G("end");if(C.tryLoc<=this.prev){var R=Va.call(C,"catchLoc"),ba=Va.call(C,"finallyLoc");if(R&&ba){if(this.prev<C.catchLoc)return G(C.catchLoc,!0);if(this.prev<C.finallyLoc)return G(C.finallyLoc)}else if(R){if(this.prev<C.catchLoc)return G(C.catchLoc,!0)}else if(ba){if(this.prev<C.finallyLoc)return G(C.finallyLoc)}else throw Error("try statement without catch or finally");}}},abrupt:function(E,G){for(var k=this.tryEntries.length-1;0<=k;--k){var y=this.tryEntries[k];if(y.tryLoc<=this.prev&&
Va.call(y,"finallyLoc")&&this.prev<y.finallyLoc){var C=y;break}}C&&("break"===E||"continue"===E)&&C.tryLoc<=G&&G<=C.finallyLoc&&(C=null);k=C?C.completion:{};k.type=E;k.arg=G;return C?(this.method="next",this.next=C.finallyLoc,ma):this.complete(k)},complete:function(E,G){if("throw"===E.type)throw E.arg;"break"===E.type||"continue"===E.type?this.next=E.arg:"return"===E.type?(this.rval=this.arg=E.arg,this.method="return",this.next="end"):"normal"===E.type&&G&&(this.next=G);return ma},finish:function(E){for(var G=
this.tryEntries.length-1;0<=G;--G){var k=this.tryEntries[G];if(k.finallyLoc===E)return this.complete(k.completion,k.afterLoc),Z(k),ma}},"catch":function(E){for(var G=this.tryEntries.length-1;0<=G;--G){var k=this.tryEntries[G];if(k.tryLoc===E){E=k.completion;if("throw"===E.type){var y=E.arg;Z(k)}return y}}throw Error("illegal catch attempt");},delegateYield:function(E,G,k){this.delegate={iterator:oa(E),resultName:G,nextLoc:k};"next"===this.method&&(this.arg=ea);return ma}};return m}("object"===typeof K?
K.exports:{});try{regeneratorRuntime=F}catch(m){"object"===typeof globalThis?globalThis.regeneratorRuntime=F:Function("r","regeneratorRuntime \x3d r")(F)}};
shadow$provide[11]=function(F,h,K,r){try{self["workbox:core:7.0.0"]&&_()}catch(m){}};
shadow$provide[12]=function(F,h,K,r){Object.defineProperties(r,{__esModule:{enumerable:!0,value:!0},logger:{enumerable:!0,get:function(){return null}}});h(11)};
shadow$provide[13]=function(F,h,K,r){Object.defineProperties(r,{__esModule:{enumerable:!0,value:!0},messages:{enumerable:!0,get:function(){return m}}});h(11);const m={"invalid-value":({paramName:l,validValueDescription:q,value:u})=>{if(!l||!q)throw Error("Unexpected input to 'invalid-value' error.");return`The '${l}' parameter was given a value with an `+`unexpected value. ${q} Received a value of `+`${JSON.stringify(u)}.`},"not-an-array":({moduleName:l,className:q,funcName:u,paramName:n})=>{if(!(l&&
q&&u&&n))throw Error("Unexpected input to 'not-an-array' error.");return`The parameter '${n}' passed into `+`'${l}.${q}.${u}()' must be an array.`},"incorrect-type":({expectedType:l,paramName:q,moduleName:u,className:n,funcName:w})=>{if(!(l&&q&&u&&w))throw Error("Unexpected input to 'incorrect-type' error.");return`The parameter '${q}' passed into `+`'${u}.${n?`${n}.`:""}`+`${w}()' must be of type ${l}.`},"incorrect-class":({expectedClassName:l,paramName:q,moduleName:u,className:n,funcName:w,isReturnValueProblem:D})=>
{if(!l||!u||!w)throw Error("Unexpected input to 'incorrect-class' error.");n=n?`${n}.`:"";return D?"The return value from "+`'${u}.${n}${w}()' `+`must be an instance of class ${l}.`:`The parameter '${q}' passed into `+`'${u}.${n}${w}()' `+`must be an instance of class ${l}.`},"missing-a-method":({expectedMethod:l,paramName:q,moduleName:u,className:n,funcName:w})=>{if(!(l&&q&&u&&n&&w))throw Error("Unexpected input to 'missing-a-method' error.");return`${u}.${n}.${w}() expected the `+`'${q}' parameter to expose a '${l}' method.`},
"add-to-cache-list-unexpected-type":({entry:l})=>"An unexpected entry was passed to 'workbox-precaching.PrecacheController.addToCacheList()' The entry "+`'${JSON.stringify(l)}' isn't supported. You must supply an array of `+"strings with one or more characters, objects with a url property or Request objects.","add-to-cache-list-conflicting-entries":({firstEntry:l,secondEntry:q})=>{if(!l||!q)throw Error("Unexpected input to 'add-to-cache-list-duplicate-entries' error.");return"Two of the entries passed to 'workbox-precaching.PrecacheController.addToCacheList()' had the URL "+
`${l} but different revision details. Workbox is `+"unable to cache and version the asset correctly. Please remove one of the entries."},"plugin-error-request-will-fetch":({thrownErrorMessage:l})=>{if(!l)throw Error("Unexpected input to 'plugin-error-request-will-fetch', error.");return"An error was thrown by a plugins 'requestWillFetch()' method. "+`The thrown error message was: '${l}'.`},"invalid-cache-name":({cacheNameId:l,value:q})=>{if(!l)throw Error("Expected a 'cacheNameId' for error 'invalid-cache-name'");
return"You must provide a name containing at least one character for "+`setCacheDetails({${l}: '...'}). Received a value of `+`'${JSON.stringify(q)}'`},"unregister-route-but-not-found-with-method":({method:l})=>{if(!l)throw Error("Unexpected input to 'unregister-route-but-not-found-with-method' error.");return"The route you're trying to unregister was not  previously "+`registered for the method type '${l}'.`},"unregister-route-route-not-registered":()=>"The route you're trying to unregister was not previously registered.",
"queue-replay-failed":({name:l})=>`Replaying the background sync queue '${l}' failed.`,"duplicate-queue-name":({name:l})=>`The Queue name '${l}' is already being used. `+"All instances of backgroundSync.Queue must be given unique names.","expired-test-without-max-age":({methodName:l,paramName:q})=>`The '${l}()' method can only be used when the `+`'${q}' is used in the constructor.`,"unsupported-route-type":({moduleName:l,className:q,funcName:u,paramName:n})=>`The supplied '${n}' parameter was an unsupported type. `+
`Please check the docs for ${l}.${q}.${u} for `+"valid input types.","not-array-of-class":({value:l,expectedClass:q,moduleName:u,className:n,funcName:w,paramName:D})=>`The supplied '${D}' parameter must be an array of `+`'${q}' objects. Received '${JSON.stringify(l)},'. `+`Please check the call to ${u}.${n}.${w}() `+"to fix the issue.","max-entries-or-age-required":({moduleName:l,className:q,funcName:u})=>"You must define either config.maxEntries or config.maxAgeSeconds"+`in ${l}.${q}.${u}`,"statuses-or-headers-required":({moduleName:l,
className:q,funcName:u})=>"You must define either config.statuses or config.headers"+`in ${l}.${q}.${u}`,"invalid-string":({moduleName:l,funcName:q,paramName:u})=>{if(!u||!l||!q)throw Error("Unexpected input to 'invalid-string' error.");return`When using strings, the '${u}' parameter must start with `+"'http' (for cross-origin matches) or '/' (for same-origin matches). "+`Please see the docs for ${l}.${q}() for `+"more info."},"channel-name-required":()=>"You must provide a channelName to construct a BroadcastCacheUpdate instance.",
"invalid-responses-are-same-args":()=>"The arguments passed into responsesAreSame() appear to be invalid. Please ensure valid Responses are used.","expire-custom-caches-only":()=>"You must provide a 'cacheName' property when using the expiration plugin with a runtime caching strategy.","unit-must-be-bytes":({normalizedRangeHeader:l})=>{if(!l)throw Error("Unexpected input to 'unit-must-be-bytes' error.");return"The 'unit' portion of the Range header must be set to 'bytes'. "+`The Range header provided was "${l}"`},
"single-range-only":({normalizedRangeHeader:l})=>{if(!l)throw Error("Unexpected input to 'single-range-only' error.");return"Multiple ranges are not supported. Please use a  single start value, and optional end value. The Range header provided was "+`"${l}"`},"invalid-range-values":({normalizedRangeHeader:l})=>{if(!l)throw Error("Unexpected input to 'invalid-range-values' error.");return"The Range header is missing both start and end values. At least one of those values is needed. The Range header provided was "+
`"${l}"`},"no-range-header":()=>"No Range header was found in the Request provided.","range-not-satisfiable":({size:l,start:q,end:u})=>`The start (${q}) and end (${u}) values in the Range are `+`not satisfiable by the cached response, which is ${l} bytes.`,"attempt-to-cache-non-get-request":({url:l,method:q})=>`Unable to cache '${l}' because it is a '${q}' request and `+"only 'GET' requests can be cached.","cache-put-with-no-response":({url:l})=>`There was an attempt to cache '${l}' but the response was not `+
"defined.","no-response":({url:l,error:q})=>{l=`The strategy could not generate a response for '${l}'.`;q&&(l+=` The underlying error is ${q}.`);return l},"bad-precaching-response":({url:l,status:q})=>`The precaching request for '${l}' failed`+(q?` with an HTTP status of ${q}.`:"."),"non-precached-url":({url:l})=>`createHandlerBoundToURL('${l}') was called, but that URL is `+"not precached. Please pass in a URL that is precached instead.","add-to-cache-list-conflicting-integrities":({url:l})=>"Two of the entries passed to 'workbox-precaching.PrecacheController.addToCacheList()' had the URL "+
`${l} with different integrity values. Please remove one of them.`,"missing-precache-entry":({cacheName:l,url:q})=>`Unable to find a precached response in ${l} for ${q}.`,"cross-origin-copy-response":({origin:l})=>"workbox-core.copyResponse() can only be used with same-origin "+`responses. It was passed a response with origin ${l}.`,"opaque-streams-source":({type:l})=>{const q="One of the workbox-streams sources resulted in an "+`'${l}' response.`;return"opaqueredirect"===l?`${q} Please do not use a navigation request that results `+
"in a redirect as a source.":`${q} Please ensure your sources are CORS-enabled.`}}};
shadow$provide[14]=function(F,h,K,r){Object.defineProperties(r,{__esModule:{enumerable:!0,value:!0},messageGenerator:{enumerable:!0,get:function(){return m}}});h(13);h(11);const m=(l,...q)=>{0<q.length&&(l+=` :: ${JSON.stringify(q)}`);return l}};
shadow$provide[15]=function(F,h,K,r){Object.defineProperties(r,{__esModule:{enumerable:!0,value:!0},WorkboxError:{enumerable:!0,get:function(){return l}}});var m=h(14);h(11);class l extends Error{constructor(q,u){super((0,m.messageGenerator)(q,u));this.name=q;this.details=u}}};
shadow$provide[16]=function(F,h,K,r){Object.defineProperties(r,{__esModule:{enumerable:!0,value:!0},assert:{enumerable:!0,get:function(){return null}}});h(15);h(11)};
shadow$provide[17]=function(F,h,K,r){Object.defineProperties(r,{__esModule:{enumerable:!0,value:!0},quotaErrorCallbacks:{enumerable:!0,get:function(){return m}}});h(11);const m=new Set};
shadow$provide[18]=function(F,h,K,r){function m(q){l.quotaErrorCallbacks.add(q)}Object.defineProperties(r,{__esModule:{enumerable:!0,value:!0},registerQuotaErrorCallback:{enumerable:!0,get:function(){return m}}});h(12);h(16);var l=h(17);h(11)};
shadow$provide[19]=function(F,h,K,r){Object.defineProperties(r,{__esModule:{enumerable:!0,value:!0},cacheNames:{enumerable:!0,get:function(){return u}}});h(11);const m={googleAnalytics:"googleAnalytics",precache:"precache-v2",prefix:"workbox",runtime:"runtime",suffix:"undefined"!==typeof registration?registration.scope:""},l=n=>[m.prefix,n,m.suffix].filter(w=>w&&0<w.length).join("-"),q=n=>{for(const w of Object.keys(m))n(w)},u={updateDetails:n=>{q(w=>{"string"===typeof n[w]&&(m[w]=n[w])})},getGoogleAnalyticsName:n=>
n||l(m.googleAnalytics),getPrecacheName:n=>n||l(m.precache),getPrefix:()=>m.prefix,getRuntimeName:n=>n||l(m.runtime),getSuffix:()=>m.suffix}};
shadow$provide[20]=function(F,h,K,r){function m(q,u){q=new URL(q);for(const n of u)q.searchParams.delete(n);return q.href}async function l(q,u,n,w){const D=m(u.url,n);if(u.url===D)return q.match(u,w);const N=Object.assign(Object.assign({},w),{ignoreSearch:!0});u=await q.keys(u,N);for(const A of u)if(u=m(A.url,n),D===u)return q.match(A,w)}Object.defineProperties(r,{__esModule:{enumerable:!0,value:!0},cacheMatchIgnoreParams:{enumerable:!0,get:function(){return l}}});h(11)};
shadow$provide[21]=function(F,h,K,r){function m(){if(void 0===l)try{new ReadableStream({start(){}}),l=!0}catch(q){l=!1}return l}Object.defineProperties(r,{__esModule:{enumerable:!0,value:!0},canConstructReadableStream:{enumerable:!0,get:function(){return m}}});h(11);let l};
shadow$provide[22]=function(F,h,K,r){function m(){if(void 0===l){const q=new Response("");if("body"in q)try{new Response(q.body),l=!0}catch(u){l=!1}l=!1}return l}Object.defineProperties(r,{__esModule:{enumerable:!0,value:!0},canConstructResponseFromBodyStream:{enumerable:!0,get:function(){return m}}});h(11);let l};
shadow$provide[23]=function(F,h,K,r){function m(l){void l.then(()=>{})}Object.defineProperties(r,{__esModule:{enumerable:!0,value:!0},dontWaitFor:{enumerable:!0,get:function(){return m}}});h(11)};
shadow$provide[24]=function(F,h,K,r){Object.defineProperties(r,{__esModule:{enumerable:!0,value:!0},Deferred:{enumerable:!0,get:function(){return m}}});h(11);class m{constructor(){this.promise=new Promise((l,q)=>{this.resolve=l;this.reject=q})}}};
shadow$provide[25]=function(F,h,K,r){async function m(){for(const q of l.quotaErrorCallbacks)await q()}Object.defineProperties(r,{__esModule:{enumerable:!0,value:!0},executeQuotaErrorCallbacks:{enumerable:!0,get:function(){return m}}});h(12);var l=h(17);h(11)};
shadow$provide[26]=function(F,h,K,r){Object.defineProperties(r,{__esModule:{enumerable:!0,value:!0},getFriendlyURL:{enumerable:!0,get:function(){return m}}});h(11);const m=l=>(new URL(String(l),location.href)).href.replace(new RegExp(`^${location.origin}`),"")};
shadow$provide[27]=function(F,h,K,r){function m(l){return new Promise(q=>setTimeout(q,l))}Object.defineProperties(r,{__esModule:{enumerable:!0,value:!0},timeout:{enumerable:!0,get:function(){return m}}});h(11)};
shadow$provide[28]=function(F,h,K,r){async function m(q){if(q){for(var u=await self.clients.matchAll({type:"window"}),n=new Set(u.map(N=>N.id)),w,D=performance.now();2E3>performance.now()-D;){u=await self.clients.matchAll({type:"window"});if(w=u.find(N=>q?N.id===q:!n.has(N.id)))break;await (0,l.timeout)(100)}return w}}Object.defineProperties(r,{__esModule:{enumerable:!0,value:!0},resultingClientExists:{enumerable:!0,get:function(){return m}}});var l=h(27);h(11)};
shadow$provide[29]=function(F,h,K,r){function m(l,q){q=q();l.waitUntil(q);return q}Object.defineProperties(r,{__esModule:{enumerable:!0,value:!0},waitUntil:{enumerable:!0,get:function(){return m}}});h(11)};
shadow$provide[30]=function(F,h,K,r){Object.defineProperties(r,{__esModule:{enumerable:!0,value:!0},Deferred:{enumerable:!0,get:function(){return D.Deferred}},WorkboxError:{enumerable:!0,get:function(){return ja.WorkboxError}},assert:{enumerable:!0,get:function(){return m.assert}},cacheMatchIgnoreParams:{enumerable:!0,get:function(){return q.cacheMatchIgnoreParams}},cacheNames:{enumerable:!0,get:function(){return l.cacheNames}},canConstructReadableStream:{enumerable:!0,get:function(){return u.canConstructReadableStream}},
canConstructResponseFromBodyStream:{enumerable:!0,get:function(){return n.canConstructResponseFromBodyStream}},dontWaitFor:{enumerable:!0,get:function(){return w.dontWaitFor}},executeQuotaErrorCallbacks:{enumerable:!0,get:function(){return N.executeQuotaErrorCallbacks}},getFriendlyURL:{enumerable:!0,get:function(){return A.getFriendlyURL}},logger:{enumerable:!0,get:function(){return L.logger}},resultingClientExists:{enumerable:!0,get:function(){return O.resultingClientExists}},timeout:{enumerable:!0,
get:function(){return Y.timeout}},waitUntil:{enumerable:!0,get:function(){return Z.waitUntil}}});var m=h(16),l=h(19),q=h(20),u=h(21),n=h(22),w=h(23),D=h(24),N=h(25),A=h(26),L=h(12),O=h(28),Y=h(27),Z=h(29),ja=h(15);h(11)};
shadow$provide[31]=function(F,h,K,r){Object.defineProperties(r,{__esModule:{enumerable:!0,value:!0},cacheNames:{enumerable:!0,get:function(){return l}}});var m=h(19);h(11);const l={get googleAnalytics(){return m.cacheNames.getGoogleAnalyticsName()},get precache(){return m.cacheNames.getPrecacheName()},get prefix(){return m.cacheNames.getPrefix()},get runtime(){return m.cacheNames.getRuntimeName()},get suffix(){return m.cacheNames.getSuffix()}}};
shadow$provide[32]=function(F,h,K,r){async function m(u,n){var w=null;u.url&&(w=(new URL(u.url)).origin);if(w!==self.location.origin)throw new q.WorkboxError("cross-origin-copy-response",{origin:w});u=u.clone();w={headers:new Headers(u.headers),status:u.status,statusText:u.statusText};n=n?n(w):w;u=(0,l.canConstructResponseFromBodyStream)()?u.body:await u.blob();return new Response(u,n)}Object.defineProperties(r,{__esModule:{enumerable:!0,value:!0},copyResponse:{enumerable:!0,get:function(){return m}}});
var l=h(22),q=h(15);h(11)};
shadow$provide[33]=function(F,h,K,r){function m(){self.addEventListener("activate",()=>self.clients.claim())}Object.defineProperties(r,{__esModule:{enumerable:!0,value:!0},clientsClaim:{enumerable:!0,get:function(){return m}}});h(11)};
shadow$provide[34]=function(F,h,K,r){function m(q){l.cacheNames.updateDetails(q)}Object.defineProperties(r,{__esModule:{enumerable:!0,value:!0},setCacheNameDetails:{enumerable:!0,get:function(){return m}}});h(16);var l=h(19);h(15);h(11)};
shadow$provide[35]=function(F,h,K,r){function m(){void self.skipWaiting()}Object.defineProperties(r,{__esModule:{enumerable:!0,value:!0},skipWaiting:{enumerable:!0,get:function(){return m}}});h(12);h(11)};
shadow$provide[36]=function(F,h,K,r){h(11)};
shadow$provide[37]=function(F,h,K,r){Object.defineProperties(r,{__esModule:{enumerable:!0,value:!0},_private:{enumerable:!0,get:function(){return l}},cacheNames:{enumerable:!0,get:function(){return q.cacheNames}},clientsClaim:{enumerable:!0,get:function(){return n.clientsClaim}},copyResponse:{enumerable:!0,get:function(){return u.copyResponse}},registerQuotaErrorCallback:{enumerable:!0,get:function(){return m.registerQuotaErrorCallback}},setCacheNameDetails:{enumerable:!0,get:function(){return w.setCacheNameDetails}},
skipWaiting:{enumerable:!0,get:function(){return D.skipWaiting}}});var m=h(18),l=h(30),q=h(31),u=h(32),n=h(33),w=h(34),D=h(35);h(11);F=h(36);h.exportCopy(K,F)};
shadow$provide[38]=function(F,h,K,r){try{self["workbox:routing:7.0.0"]&&_()}catch(m){}};
shadow$provide[39]=function(F,h,K,r){Object.defineProperties(r,{__esModule:{enumerable:!0,value:!0},defaultMethod:{enumerable:!0,get:function(){return"GET"}},validMethods:{enumerable:!0,get:function(){return m}}});h(38);const m="DELETE GET HEAD PATCH POST PUT".split(" ")};
shadow$provide[40]=function(F,h,K,r){Object.defineProperties(r,{__esModule:{enumerable:!0,value:!0},normalizeHandler:{enumerable:!0,get:function(){return m}}});h(16);h(38);const m=l=>l&&"object"===typeof l?l:{handle:l}};
shadow$provide[41]=function(F,h,K,r){Object.defineProperties(r,{__esModule:{enumerable:!0,value:!0},Route:{enumerable:!0,get:function(){return q}}});h(16);var m=h(39),l=h(40);h(38);class q{constructor(u,n,w=m.defaultMethod){this.handler=(0,l.normalizeHandler)(n);this.match=u;this.method=w}setCatchHandler(u){this.catchHandler=(0,l.normalizeHandler)(u)}}};
shadow$provide[42]=function(F,h,K,r){Object.defineProperties(r,{__esModule:{enumerable:!0,value:!0},NavigationRoute:{enumerable:!0,get:function(){return m}}});h(16);h(12);F=h(41);h(38);class m extends F.Route{constructor(l,{allowlist:q=[/./],denylist:u=[]}={}){super(n=>this._match(n),l);this._allowlist=q;this._denylist=u}_match({url:l,request:q}){if(q&&"navigate"!==q.mode)return!1;const u=l.pathname+l.search;for(const n of this._denylist)if(n.test(u))return!1;return this._allowlist.some(n=>n.test(u))?
!0:!1}}};
shadow$provide[43]=function(F,h,K,r){Object.defineProperties(r,{__esModule:{enumerable:!0,value:!0},RegExpRoute:{enumerable:!0,get:function(){return m}}});h(16);h(12);F=h(41);h(38);class m extends F.Route{constructor(l,q,u){super(({url:n})=>{const w=l.exec(n.href);if(w&&(n.origin===location.origin||0===w.index))return w.slice(1)},q,u)}}};
shadow$provide[44]=function(F,h,K,r){Object.defineProperties(r,{__esModule:{enumerable:!0,value:!0},Router:{enumerable:!0,get:function(){return u}}});h(16);h(26);var m=h(39);h(12);var l=h(40),q=h(15);h(38);class u{constructor(){this._routes=new Map;this._defaultHandlerMap=new Map}get routes(){return this._routes}addFetchListener(){self.addEventListener("fetch",n=>{var {request:w}=n;(w=this.handleRequest({request:w,event:n}))&&n.respondWith(w)})}addCacheListener(){self.addEventListener("message",n=>
{if(n.data&&"CACHE_URLS"===n.data.type){var {payload:w}=n.data;w=Promise.all(w.urlsToCache.map(D=>{"string"===typeof D&&(D=[D]);D=new Request(...D);return this.handleRequest({request:D,event:n})}));n.waitUntil(w);n.ports&&n.ports[0]&&void w.then(()=>n.ports[0].postMessage(!0))}})}handleRequest({request:n,event:w}){const D=new URL(n.url,location.href);if(D.protocol.startsWith("http")){var {params:N,route:A}=this.findMatchingRoute({event:w,request:n,sameOrigin:D.origin===location.origin,url:D}),L=A&&
A.handler,O=n.method;!L&&this._defaultHandlerMap.has(O)&&(L=this._defaultHandlerMap.get(O));if(L){try{var Y=L.handle({url:D,request:n,event:w,params:N})}catch(ja){Y=Promise.reject(ja)}var Z=A&&A.catchHandler;Y instanceof Promise&&(this._catchHandler||Z)&&(Y=Y.catch(async ja=>{if(Z)try{return await Z.handle({url:D,request:n,event:w,params:N})}catch(oa){oa instanceof Error&&(ja=oa)}if(this._catchHandler)return this._catchHandler.handle({url:D,request:n,event:w});throw ja;}));return Y}}}findMatchingRoute({url:n,
sameOrigin:w,request:D,event:N}){var A=this._routes.get(D.method)||[];for(const L of A)if(A=L.match({url:n,sameOrigin:w,request:D,event:N}))return n=A,Array.isArray(n)&&0===n.length?n=void 0:A.constructor===Object&&0===Object.keys(A).length?n=void 0:"boolean"===typeof A&&(n=void 0),{route:L,params:n};return{}}setDefaultHandler(n,w=m.defaultMethod){this._defaultHandlerMap.set(w,(0,l.normalizeHandler)(n))}setCatchHandler(n){this._catchHandler=(0,l.normalizeHandler)(n)}registerRoute(n){this._routes.has(n.method)||
this._routes.set(n.method,[]);this._routes.get(n.method).push(n)}unregisterRoute(n){if(!this._routes.has(n.method))throw new q.WorkboxError("unregister-route-but-not-found-with-method",{method:n.method});const w=this._routes.get(n.method).indexOf(n);if(-1<w)this._routes.get(n.method).splice(w,1);else throw new q.WorkboxError("unregister-route-route-not-registered");}}};
shadow$provide[45]=function(F,h,K,r){Object.defineProperties(r,{__esModule:{enumerable:!0,value:!0},getOrCreateDefaultRouter:{enumerable:!0,get:function(){return q}}});var m=h(44);h(38);let l;const q=()=>{l||(l=new m.Router,l.addFetchListener(),l.addCacheListener());return l}};
shadow$provide[46]=function(F,h,K,r){function m(w,D,N){if("string"===typeof w){const A=new URL(w,location.href);w=new q.Route(({url:L})=>L.href===A.href,D,N)}else if(w instanceof RegExp)w=new u.RegExpRoute(w,D,N);else if("function"===typeof w)w=new q.Route(w,D,N);else if(!(w instanceof q.Route))throw new l.WorkboxError("unsupported-route-type",{moduleName:"workbox-routing",funcName:"registerRoute",paramName:"capture"});(0,n.getOrCreateDefaultRouter)().registerRoute(w);return w}Object.defineProperties(r,
{__esModule:{enumerable:!0,value:!0},registerRoute:{enumerable:!0,get:function(){return m}}});h(12);var l=h(15),q=h(41),u=h(43),n=h(45);h(38)};
shadow$provide[47]=function(F,h,K,r){function m(q){(0,l.getOrCreateDefaultRouter)().setCatchHandler(q)}Object.defineProperties(r,{__esModule:{enumerable:!0,value:!0},setCatchHandler:{enumerable:!0,get:function(){return m}}});var l=h(45);h(38)};
shadow$provide[48]=function(F,h,K,r){function m(q){(0,l.getOrCreateDefaultRouter)().setDefaultHandler(q)}Object.defineProperties(r,{__esModule:{enumerable:!0,value:!0},setDefaultHandler:{enumerable:!0,get:function(){return m}}});var l=h(45);h(38)};
shadow$provide[49]=function(F,h,K,r){Object.defineProperties(r,{__esModule:{enumerable:!0,value:!0},NavigationRoute:{enumerable:!0,get:function(){return m.NavigationRoute}},RegExpRoute:{enumerable:!0,get:function(){return l.RegExpRoute}},Route:{enumerable:!0,get:function(){return u.Route}},Router:{enumerable:!0,get:function(){return n.Router}},registerRoute:{enumerable:!0,get:function(){return q.registerRoute}},setCatchHandler:{enumerable:!0,get:function(){return w.setCatchHandler}},setDefaultHandler:{enumerable:!0,
get:function(){return D.setDefaultHandler}}});var m=h(42),l=h(43),q=h(46),u=h(41),n=h(44),w=h(47),D=h(48);h(38)};
shadow$provide[50]=function(F,h,K,r){try{self["workbox:precaching:7.0.0"]&&_()}catch(m){}};
shadow$provide[51]=function(F,h,K,r){function m(q){if(!q)throw new l.WorkboxError("add-to-cache-list-unexpected-type",{entry:q});if("string"===typeof q)return q=new URL(q,location.href),{cacheKey:q.href,url:q.href};const {revision:u,url:n}=q;if(!n)throw new l.WorkboxError("add-to-cache-list-unexpected-type",{entry:q});if(!u)return q=new URL(n,location.href),{cacheKey:q.href,url:q.href};q=new URL(n,location.href);const w=new URL(n,location.href);q.searchParams.set("__WB_REVISION__",u);return{cacheKey:q.href,
url:w.href}}Object.defineProperties(r,{__esModule:{enumerable:!0,value:!0},createCacheKey:{enumerable:!0,get:function(){return m}}});var l=h(15);h(50)};
shadow$provide[52]=function(F,h,K,r){Object.defineProperties(r,{__esModule:{enumerable:!0,value:!0},PrecacheInstallReportPlugin:{enumerable:!0,get:function(){return m}}});h(50);class m{constructor(){this.updatedURLs=[];this.notUpdatedURLs=[];this.handlerWillStart=async({request:l,state:q})=>{q&&(q.originalRequest=l)};this.cachedResponseWillBeUsed=async({event:l,state:q,cachedResponse:u})=>{"install"===l.type&&q&&q.originalRequest&&q.originalRequest instanceof Request&&(l=q.originalRequest.url,u?this.notUpdatedURLs.push(l):
this.updatedURLs.push(l));return u}}}};
shadow$provide[53]=function(F,h,K,r){Object.defineProperties(r,{__esModule:{enumerable:!0,value:!0},PrecacheCacheKeyPlugin:{enumerable:!0,get:function(){return m}}});h(50);class m{constructor({precacheController:l}){this.cacheKeyWillBeUsed=async({request:q,params:u})=>(u=(null===u||void 0===u?void 0:u.cacheKey)||this._precacheController.getCacheKeyForURL(q.url))?new Request(u,{headers:q.headers}):q;this._precacheController=l}}};
shadow$provide[54]=function(F,h,K,r){function m(q){const u=q.length;if(0<u){l.logger.groupCollapsed("During precaching cleanup, "+`${u} cached `+`request${1===u?" was":"s were"} deleted.`);l.logger.groupCollapsed("Deleted Cache Requests");for(const n of q)l.logger.log(n);l.logger.groupEnd();l.logger.groupEnd()}}Object.defineProperties(r,{__esModule:{enumerable:!0,value:!0},printCleanupDetails:{enumerable:!0,get:function(){return m}}});var l=h(12);h(50)};
shadow$provide[55]=function(F,h,K,r){function m(u,n){if(0!==n.length){q.logger.groupCollapsed(u);for(const w of n)q.logger.log(w);q.logger.groupEnd()}}function l(u,n){var w=u.length;const D=n.length;if(w||D)w=`Precaching ${w} file${1===w?"":"s"}.`,0<D&&(w+=` ${D} `+`file${1===D?" is":"s are"} already cached.`),q.logger.groupCollapsed(w),m("View newly precached URLs.",u),m("View previously precached URLs.",n),q.logger.groupEnd()}Object.defineProperties(r,{__esModule:{enumerable:!0,value:!0},printInstallDetails:{enumerable:!0,
get:function(){return l}}});var q=h(12);h(50)};
shadow$provide[56]=function(F,h,K,r){try{self["workbox:strategies:7.0.0"]&&_()}catch(m){}};
shadow$provide[57]=function(F,h,K,r){function m(A){return"string"===typeof A?new Request(A):A}Object.defineProperties(r,{__esModule:{enumerable:!0,value:!0},StrategyHandler:{enumerable:!0,get:function(){return N}}});h(16);var l=h(20),q=h(24),u=h(25),n=h(26);h(12);var w=h(27),D=h(15);h(56);class N{constructor(A,L){this._cacheKeys={};Object.assign(this,L);this.event=L.event;this._strategy=A;this._handlerDeferred=new q.Deferred;this._extendLifetimePromises=[];this._plugins=[...A.plugins];this._pluginStateMap=
new Map;for(const O of this._plugins)this._pluginStateMap.set(O,{});this.event.waitUntil(this._handlerDeferred.promise)}async fetch(A){const {event:L}=this;A=m(A);if("navigate"===A.mode&&L instanceof FetchEvent&&L.preloadResponse){var O=await L.preloadResponse;if(O)return O}O=this.hasCallback("fetchDidFail")?A.clone():null;try{for(var Y of this.iterateCallbacks("requestWillFetch"))A=await Y({request:A.clone(),event:L})}catch(Z){if(Z instanceof Error)throw new D.WorkboxError("plugin-error-request-will-fetch",
{thrownErrorMessage:Z.message});}Y=A.clone();try{let Z;Z=await fetch(A,"navigate"===A.mode?void 0:this._strategy.fetchOptions);for(const ja of this.iterateCallbacks("fetchDidSucceed"))Z=await ja({event:L,request:Y,response:Z});return Z}catch(Z){throw O&&await this.runCallbacks("fetchDidFail",{error:Z,event:L,originalRequest:O.clone(),request:Y.clone()}),Z;}}async fetchAndCachePut(A){const L=await this.fetch(A),O=L.clone();void this.waitUntil(this.cachePut(A,O));return L}async cacheMatch(A){A=m(A);
const {cacheName:L,matchOptions:O}=this._strategy;A=await this.getCacheKey(A,"read");var Y=Object.assign(Object.assign({},O),{cacheName:L});Y=await caches.match(A,Y);for(const Z of this.iterateCallbacks("cachedResponseWillBeUsed"))Y=await Z({cacheName:L,matchOptions:O,cachedResponse:Y,request:A,event:this.event})||void 0;return Y}async cachePut(A,L){A=m(A);await (0,w.timeout)(0);A=await this.getCacheKey(A,"write");if(!L)throw new D.WorkboxError("cache-put-with-no-response",{url:(0,n.getFriendlyURL)(A.url)});
L=await this._ensureResponseSafeToCache(L);if(!L)return!1;const {cacheName:O,matchOptions:Y}=this._strategy,Z=await self.caches.open(O),ja=this.hasCallback("cacheDidUpdate"),oa=ja?await (0,l.cacheMatchIgnoreParams)(Z,A.clone(),["__WB_REVISION__"],Y):null;try{await Z.put(A,ja?L.clone():L)}catch(ka){if(ka instanceof Error)throw"QuotaExceededError"===ka.name&&await (0,u.executeQuotaErrorCallbacks)(),ka;}for(const ka of this.iterateCallbacks("cacheDidUpdate"))await ka({cacheName:O,oldResponse:oa,newResponse:L.clone(),
request:A,event:this.event});return!0}async getCacheKey(A,L){const O=`${A.url} | ${L}`;if(!this._cacheKeys[O]){for(const Y of this.iterateCallbacks("cacheKeyWillBeUsed"))A=m(await Y({mode:L,request:A,event:this.event,params:this.params}));this._cacheKeys[O]=A}return this._cacheKeys[O]}hasCallback(A){for(const L of this._strategy.plugins)if(A in L)return!0;return!1}async runCallbacks(A,L){for(const O of this.iterateCallbacks(A))await O(L)}*iterateCallbacks(A){for(const L of this._strategy.plugins)if("function"===
typeof L[A]){const O=this._pluginStateMap.get(L);yield(Y=>{Y=Object.assign(Object.assign({},Y),{state:O});return L[A](Y)})}}waitUntil(A){this._extendLifetimePromises.push(A);return A}async doneWaiting(){let A;for(;A=this._extendLifetimePromises.shift();)await A}destroy(){this._handlerDeferred.resolve(null)}async _ensureResponseSafeToCache(A){let L=!1;for(const O of this.iterateCallbacks("cacheWillUpdate"))if(A=await O({request:this.request,response:A,event:this.event})||void 0,L=!0,!A)break;L||A&&
200!==A.status&&(A=void 0);return A}}};
shadow$provide[58]=function(F,h,K,r){Object.defineProperties(r,{__esModule:{enumerable:!0,value:!0},Strategy:{enumerable:!0,get:function(){return u}}});var m=h(19),l=h(15);h(12);h(26);var q=h(57);h(56);class u{constructor(n={}){this.cacheName=m.cacheNames.getRuntimeName(n.cacheName);this.plugins=n.plugins||[];this.fetchOptions=n.fetchOptions;this.matchOptions=n.matchOptions}handle(n){[n]=this.handleAll(n);return n}handleAll(n){n instanceof FetchEvent&&(n={event:n,request:n.request});var w=n.event;
const D="string"===typeof n.request?new Request(n.request):n.request,N=new q.StrategyHandler(this,{event:w,request:D,params:"params"in n?n.params:void 0});n=this._getResponse(N,D,w);w=this._awaitComplete(n,N,D,w);return[n,w]}async _getResponse(n,w,D){await n.runCallbacks("handlerWillStart",{event:D,request:w});let N=void 0;try{if(N=await this._handle(w,n),!N||"error"===N.type)throw new l.WorkboxError("no-response",{url:w.url});}catch(A){if(A instanceof Error)for(const L of n.iterateCallbacks("handlerDidError"))if(N=
await L({error:A,event:D,request:w}))break;if(!N)throw A;}for(const A of n.iterateCallbacks("handlerWillRespond"))N=await A({event:D,request:w,response:N});return N}async _awaitComplete(n,w,D,N){let A,L;try{A=await n}catch(O){}try{await w.runCallbacks("handlerDidRespond",{event:N,request:D,response:A}),await w.doneWaiting()}catch(O){O instanceof Error&&(L=O)}await w.runCallbacks("handlerDidComplete",{event:N,request:D,response:A,error:L});w.destroy();if(L)throw L;}}};
shadow$provide[59]=function(F,h,K,r){Object.defineProperties(r,{__esModule:{enumerable:!0,value:!0},PrecacheStrategy:{enumerable:!0,get:function(){return u}}});var m=h(32),l=h(19);h(26);h(12);var q=h(15);F=h(58);h(50);class u extends F.Strategy{constructor(n={}){n.cacheName=l.cacheNames.getPrecacheName(n.cacheName);super(n);this._fallbackToNetwork=!1===n.fallbackToNetwork?!1:!0;this.plugins.push(u.copyRedirectedCacheableResponsesPlugin)}async _handle(n,w){const D=await w.cacheMatch(n);return D?D:
w.event&&"install"===w.event.type?await this._handleInstall(n,w):await this._handleFetch(n,w)}async _handleFetch(n,w){var D=w.params||{};if(this._fallbackToNetwork){D=D.integrity;var N=n.integrity;const A=!N||N===D;N=await w.fetch(new Request(n,{integrity:"no-cors"!==n.mode?N||D:void 0}));D&&A&&"no-cors"!==n.mode&&(this._useDefaultCacheabilityPluginIfNeeded(),await w.cachePut(n,N.clone()))}else throw new q.WorkboxError("missing-precache-entry",{cacheName:this.cacheName,url:n.url});return N}async _handleInstall(n,
w){this._useDefaultCacheabilityPluginIfNeeded();const D=await w.fetch(n);if(!await w.cachePut(n,D.clone()))throw new q.WorkboxError("bad-precaching-response",{url:n.url,status:D.status});return D}_useDefaultCacheabilityPluginIfNeeded(){let n=null,w=0;for(const [D,N]of this.plugins.entries())N!==u.copyRedirectedCacheableResponsesPlugin&&(N===u.defaultPrecacheCacheabilityPlugin&&(n=D),N.cacheWillUpdate&&w++);0===w?this.plugins.push(u.defaultPrecacheCacheabilityPlugin):1<w&&null!==n&&this.plugins.splice(n,
1)}}u.defaultPrecacheCacheabilityPlugin={async cacheWillUpdate({response:n}){return!n||400<=n.status?null:n}};u.copyRedirectedCacheableResponsesPlugin={async cacheWillUpdate({response:n}){return n.redirected?await (0,m.copyResponse)(n):n}}};
shadow$provide[60]=function(F,h,K,r){Object.defineProperties(r,{__esModule:{enumerable:!0,value:!0},PrecacheController:{enumerable:!0,get:function(){return N}}});h(16);var m=h(19);h(12);var l=h(15),q=h(29),u=h(51),n=h(52),w=h(53);h(54);h(55);var D=h(59);h(50);class N{constructor({cacheName:A,plugins:L=[],fallbackToNetwork:O=!0}={}){this._urlsToCacheKeys=new Map;this._urlsToCacheModes=new Map;this._cacheKeysToIntegrities=new Map;this._strategy=new D.PrecacheStrategy({cacheName:m.cacheNames.getPrecacheName(A),
plugins:[...L,new w.PrecacheCacheKeyPlugin({precacheController:this})],fallbackToNetwork:O});this.install=this.install.bind(this);this.activate=this.activate.bind(this)}get strategy(){return this._strategy}precache(A){this.addToCacheList(A);this._installAndActiveListenersAdded||(self.addEventListener("install",this.install),self.addEventListener("activate",this.activate),this._installAndActiveListenersAdded=!0)}addToCacheList(A){const L=[];for(const O of A){"string"===typeof O?L.push(O):O&&void 0===
O.revision&&L.push(O.url);const {cacheKey:Y,url:Z}=(0,u.createCacheKey)(O);A="string"!==typeof O&&O.revision?"reload":"default";if(this._urlsToCacheKeys.has(Z)&&this._urlsToCacheKeys.get(Z)!==Y)throw new l.WorkboxError("add-to-cache-list-conflicting-entries",{firstEntry:this._urlsToCacheKeys.get(Z),secondEntry:Y});if("string"!==typeof O&&O.integrity){if(this._cacheKeysToIntegrities.has(Y)&&this._cacheKeysToIntegrities.get(Y)!==O.integrity)throw new l.WorkboxError("add-to-cache-list-conflicting-integrities",
{url:Z});this._cacheKeysToIntegrities.set(Y,O.integrity)}this._urlsToCacheKeys.set(Z,Y);this._urlsToCacheModes.set(Z,A);0<L.length&&(A="Workbox is precaching URLs without revision "+`info: ${L.join(", ")}\nThis is generally NOT safe. `+"Learn more at https://bit.ly/wb-precache",console.warn(A))}}install(A){return(0,q.waitUntil)(A,async()=>{const L=new n.PrecacheInstallReportPlugin;this.strategy.plugins.push(L);for(const [ja,oa]of this._urlsToCacheKeys){var O=this._cacheKeysToIntegrities.get(oa);const ka=
this._urlsToCacheModes.get(ja);O=new Request(ja,{integrity:O,cache:ka,credentials:"same-origin"});await Promise.all(this.strategy.handleAll({params:{cacheKey:oa},request:O,event:A}))}const {updatedURLs:Y,notUpdatedURLs:Z}=L;return{updatedURLs:Y,notUpdatedURLs:Z}})}activate(A){return(0,q.waitUntil)(A,async()=>{const L=await self.caches.open(this.strategy.cacheName),O=await L.keys(),Y=new Set(this._urlsToCacheKeys.values()),Z=[];for(const ja of O)Y.has(ja.url)||(await L.delete(ja),Z.push(ja.url));return{deletedURLs:Z}})}getURLsToCacheKeys(){return this._urlsToCacheKeys}getCachedURLs(){return[...this._urlsToCacheKeys.keys()]}getCacheKeyForURL(A){A=
new URL(A,location.href);return this._urlsToCacheKeys.get(A.href)}getIntegrityForCacheKey(A){return this._cacheKeysToIntegrities.get(A)}async matchPrecache(A){if(A=this.getCacheKeyForURL(A instanceof Request?A.url:A))return(await self.caches.open(this.strategy.cacheName)).match(A)}createHandlerBoundToURL(A){const L=this.getCacheKeyForURL(A);if(!L)throw new l.WorkboxError("non-precached-url",{url:A});return O=>{O.request=new Request(A);O.params=Object.assign({cacheKey:L},O.params);return this.strategy.handle(O)}}}
};
shadow$provide[61]=function(F,h,K,r){Object.defineProperties(r,{__esModule:{enumerable:!0,value:!0},getOrCreatePrecacheController:{enumerable:!0,get:function(){return q}}});var m=h(60);h(50);let l;const q=()=>{l||(l=new m.PrecacheController);return l}};
shadow$provide[62]=function(F,h,K,r){function m(q){(0,l.getOrCreatePrecacheController)().strategy.plugins.push(...q)}Object.defineProperties(r,{__esModule:{enumerable:!0,value:!0},addPlugins:{enumerable:!0,get:function(){return m}}});var l=h(61);h(50)};
shadow$provide[63]=function(F,h,K,r){function m(l,q=[]){for(const u of[...l.searchParams.keys()])q.some(n=>n.test(u))&&l.searchParams.delete(u);return l}Object.defineProperties(r,{__esModule:{enumerable:!0,value:!0},removeIgnoredSearchParams:{enumerable:!0,get:function(){return m}}});h(50)};
shadow$provide[64]=function(F,h,K,r){function*m(q,{ignoreURLParametersMatching:u=[/^utm_/,/^fbclid$/],directoryIndex:n="index.html",cleanURLs:w=!0,urlManipulation:D}={}){q=new URL(q,location.href);q.hash="";yield q.href;u=(0,l.removeIgnoredSearchParams)(q,u);yield u.href;if(n&&u.pathname.endsWith("/")){const N=new URL(u.href);N.pathname+=n;yield N.href}w&&(n=new URL(u.href),n.pathname+=".html",yield n.href);if(D){D=D({url:q});for(const N of D)yield N.href}}Object.defineProperties(r,{__esModule:{enumerable:!0,
value:!0},generateURLVariations:{enumerable:!0,get:function(){return m}}});var l=h(63);h(50)};
shadow$provide[65]=function(F,h,K,r){Object.defineProperties(r,{__esModule:{enumerable:!0,value:!0},PrecacheRoute:{enumerable:!0,get:function(){return l}}});h(12);h(26);F=h(41);var m=h(64);h(50);class l extends F.Route{constructor(q,u){super(({request:n})=>{var w=q.getURLsToCacheKeys();for(const D of(0,m.generateURLVariations)(n.url,u))if(n=w.get(D))return w=q.getIntegrityForCacheKey(n),{cacheKey:n,integrity:w}},q.strategy)}}};
shadow$provide[66]=function(F,h,K,r){function m(n){const w=(0,q.getOrCreatePrecacheController)();n=new u.PrecacheRoute(w,n);(0,l.registerRoute)(n)}Object.defineProperties(r,{__esModule:{enumerable:!0,value:!0},addRoute:{enumerable:!0,get:function(){return m}}});var l=h(46),q=h(61),u=h(65);h(50)};
shadow$provide[67]=function(F,h,K,r){Object.defineProperties(r,{__esModule:{enumerable:!0,value:!0},deleteOutdatedCaches:{enumerable:!0,get:function(){return m}}});h(50);const m=async(l,q="-precache-")=>{const u=(await self.caches.keys()).filter(n=>n.includes(q)&&n.includes(self.registration.scope)&&n!==l);await Promise.all(u.map(n=>self.caches.delete(n)));return u}};
shadow$provide[68]=function(F,h,K,r){function m(){self.addEventListener("activate",u=>{const n=l.cacheNames.getPrecacheName();u.waitUntil((0,q.deleteOutdatedCaches)(n).then(w=>{}))})}Object.defineProperties(r,{__esModule:{enumerable:!0,value:!0},cleanupOutdatedCaches:{enumerable:!0,get:function(){return m}}});var l=h(19);h(12);var q=h(67);h(50)};
shadow$provide[69]=function(F,h,K,r){function m(q){return(0,l.getOrCreatePrecacheController)().createHandlerBoundToURL(q)}Object.defineProperties(r,{__esModule:{enumerable:!0,value:!0},createHandlerBoundToURL:{enumerable:!0,get:function(){return m}}});var l=h(61);h(50)};
shadow$provide[70]=function(F,h,K,r){function m(q){return(0,l.getOrCreatePrecacheController)().getCacheKeyForURL(q)}Object.defineProperties(r,{__esModule:{enumerable:!0,value:!0},getCacheKeyForURL:{enumerable:!0,get:function(){return m}}});var l=h(61);h(50)};
shadow$provide[71]=function(F,h,K,r){function m(q){return(0,l.getOrCreatePrecacheController)().matchPrecache(q)}Object.defineProperties(r,{__esModule:{enumerable:!0,value:!0},matchPrecache:{enumerable:!0,get:function(){return m}}});var l=h(61);h(50)};
shadow$provide[72]=function(F,h,K,r){function m(q){(0,l.getOrCreatePrecacheController)().precache(q)}Object.defineProperties(r,{__esModule:{enumerable:!0,value:!0},precache:{enumerable:!0,get:function(){return m}}});var l=h(61);h(50)};
shadow$provide[73]=function(F,h,K,r){function m(u,n){(0,q.precache)(u);(0,l.addRoute)(n)}Object.defineProperties(r,{__esModule:{enumerable:!0,value:!0},precacheAndRoute:{enumerable:!0,get:function(){return m}}});var l=h(66),q=h(72);h(50)};
shadow$provide[74]=function(F,h,K,r){Object.defineProperties(r,{__esModule:{enumerable:!0,value:!0},PrecacheFallbackPlugin:{enumerable:!0,get:function(){return l}}});var m=h(61);h(50);class l{constructor({fallbackURL:q,precacheController:u}){this.handlerDidError=()=>this._precacheController.matchPrecache(this._fallbackURL);this._fallbackURL=q;this._precacheController=u||(0,m.getOrCreatePrecacheController)()}}};
shadow$provide[75]=function(F,h,K,r){h(50)};
shadow$provide[76]=function(F,h,K,r){Object.defineProperties(r,{__esModule:{enumerable:!0,value:!0},PrecacheController:{enumerable:!0,get:function(){return A.PrecacheController}},PrecacheFallbackPlugin:{enumerable:!0,get:function(){return Y.PrecacheFallbackPlugin}},PrecacheRoute:{enumerable:!0,get:function(){return L.PrecacheRoute}},PrecacheStrategy:{enumerable:!0,get:function(){return O.PrecacheStrategy}},addPlugins:{enumerable:!0,get:function(){return m.addPlugins}},addRoute:{enumerable:!0,get:function(){return l.addRoute}},
cleanupOutdatedCaches:{enumerable:!0,get:function(){return q.cleanupOutdatedCaches}},createHandlerBoundToURL:{enumerable:!0,get:function(){return u.createHandlerBoundToURL}},getCacheKeyForURL:{enumerable:!0,get:function(){return n.getCacheKeyForURL}},matchPrecache:{enumerable:!0,get:function(){return w.matchPrecache}},precache:{enumerable:!0,get:function(){return D.precache}},precacheAndRoute:{enumerable:!0,get:function(){return N.precacheAndRoute}}});var m=h(62),l=h(66),q=h(68),u=h(69),n=h(70),w=
h(71),D=h(72),N=h(73),A=h(60),L=h(65),O=h(59),Y=h(74);h(50);F=h(75);h.exportCopy(K,F)};
shadow$provide[77]=function(F,h,K,r){Object.defineProperties(r,{__esModule:{enumerable:!0,value:!0},messages:{enumerable:!0,get:function(){return q}}});var m=h(12),l=h(26);h(56);const q={strategyStart:(u,n)=>`Using ${u} to respond to '${(0,l.getFriendlyURL)(n.url)}'`,printFinalResponse:u=>{u&&(m.logger.groupCollapsed("View the final response here."),m.logger.log(u||"[No response returned]"),m.logger.groupEnd())}}};
shadow$provide[78]=function(F,h,K,r){Object.defineProperties(r,{__esModule:{enumerable:!0,value:!0},CacheFirst:{enumerable:!0,get:function(){return l}}});h(16);h(12);var m=h(15);F=h(58);h(77);h(56);class l extends F.Strategy{async _handle(q,u){let n=await u.cacheMatch(q),w=void 0;if(!n)try{n=await u.fetchAndCachePut(q)}catch(D){D instanceof Error&&(w=D)}if(!n)throw new m.WorkboxError("no-response",{url:q.url,error:w});return n}}};
shadow$provide[79]=function(F,h,K,r){Object.defineProperties(r,{__esModule:{enumerable:!0,value:!0},CacheOnly:{enumerable:!0,get:function(){return l}}});h(16);h(12);var m=h(15);F=h(58);h(77);h(56);class l extends F.Strategy{async _handle(q,u){u=await u.cacheMatch(q);if(!u)throw new m.WorkboxError("no-response",{url:q.url});return u}}};
shadow$provide[80]=function(F,h,K,r){Object.defineProperties(r,{__esModule:{enumerable:!0,value:!0},cacheOkAndOpaquePlugin:{enumerable:!0,get:function(){return m}}});h(56);const m={cacheWillUpdate:async({response:l})=>200===l.status||0===l.status?l:null}};
shadow$provide[81]=function(F,h,K,r){Object.defineProperties(r,{__esModule:{enumerable:!0,value:!0},NetworkFirst:{enumerable:!0,get:function(){return q}}});h(16);h(12);var m=h(15),l=h(80);F=h(58);h(77);h(56);class q extends F.Strategy{constructor(u={}){super(u);this.plugins.some(n=>"cacheWillUpdate"in n)||this.plugins.unshift(l.cacheOkAndOpaquePlugin);this._networkTimeoutSeconds=u.networkTimeoutSeconds||0}async _handle(u,n){var w=[];const D=[];let N;if(this._networkTimeoutSeconds){const {id:L,promise:O}=
this._getTimeoutPromise({request:u,logs:w,handler:n});N=L;D.push(O)}const A=this._getNetworkPromise({timeoutId:N,request:u,logs:w,handler:n});D.push(A);w=await n.waitUntil((async()=>await n.waitUntil(Promise.race(D))||await A)());if(!w)throw new m.WorkboxError("no-response",{url:u.url});return w}_getTimeoutPromise({request:u,handler:n}){let w;return{promise:new Promise(D=>{w=setTimeout(async()=>{D(await n.cacheMatch(u))},1E3*this._networkTimeoutSeconds)}),id:w}}async _getNetworkPromise({timeoutId:u,
request:n,handler:w}){let D,N;try{N=await w.fetchAndCachePut(n)}catch(A){A instanceof Error&&(D=A)}u&&clearTimeout(u);if(D||!N)N=await w.cacheMatch(n);return N}}};
shadow$provide[82]=function(F,h,K,r){Object.defineProperties(r,{__esModule:{enumerable:!0,value:!0},NetworkOnly:{enumerable:!0,get:function(){return q}}});h(16);h(12);var m=h(27),l=h(15);F=h(58);h(77);h(56);class q extends F.Strategy{constructor(u={}){super(u);this._networkTimeoutSeconds=u.networkTimeoutSeconds||0}async _handle(u,n){let w=void 0,D;try{const N=[n.fetch(u)];if(this._networkTimeoutSeconds){const A=(0,m.timeout)(1E3*this._networkTimeoutSeconds);N.push(A)}D=await Promise.race(N);if(!D)throw Error("Timed out the network response after "+
`${this._networkTimeoutSeconds} seconds.`);}catch(N){N instanceof Error&&(w=N)}if(!D)throw new l.WorkboxError("no-response",{url:u.url,error:w});return D}}};
shadow$provide[83]=function(F,h,K,r){Object.defineProperties(r,{__esModule:{enumerable:!0,value:!0},StaleWhileRevalidate:{enumerable:!0,get:function(){return q}}});h(16);h(12);var m=h(15),l=h(80);F=h(58);h(77);h(56);class q extends F.Strategy{constructor(u={}){super(u);this.plugins.some(n=>"cacheWillUpdate"in n)||this.plugins.unshift(l.cacheOkAndOpaquePlugin)}async _handle(u,n){const w=n.fetchAndCachePut(u).catch(()=>{});void n.waitUntil(w);n=await n.cacheMatch(u);let D;if(!n)try{n=await w}catch(N){N instanceof
Error&&(D=N)}if(!n)throw new m.WorkboxError("no-response",{url:u.url,error:D});return n}}};
shadow$provide[84]=function(F,h,K,r){Object.defineProperties(r,{__esModule:{enumerable:!0,value:!0},CacheFirst:{enumerable:!0,get:function(){return m.CacheFirst}},CacheOnly:{enumerable:!0,get:function(){return l.CacheOnly}},NetworkFirst:{enumerable:!0,get:function(){return q.NetworkFirst}},NetworkOnly:{enumerable:!0,get:function(){return u.NetworkOnly}},StaleWhileRevalidate:{enumerable:!0,get:function(){return n.StaleWhileRevalidate}},Strategy:{enumerable:!0,get:function(){return w.Strategy}},StrategyHandler:{enumerable:!0,
get:function(){return D.StrategyHandler}}});var m=h(78),l=h(79),q=h(81),u=h(82),n=h(83),w=h(58),D=h(57);h(56)};
'use strict';$APP.kg(10,{});var sN=$APP.kg(37,{});var tN=$APP.kg(49,{});var uN=$APP.kg(76,{});var vN=$APP.kg(84,{});var wN=$APP.Ig($APP.Rf.g(function(a){return["/wiki-guides",$APP.r.h(a)].join("")},new $APP.S(null,15,5,$APP.T,"/ /assets/re-com/css/bootstrap.css /assets/re-com/css/material-design-iconic-font.min.css /assets/re-com/css/re-com.css /assets/re-com/css/chosen-sprite.png /assets/re-com/css/chosen-sprite@2x.png /assets/re-com/fonts/Material-Design-Iconic-Font.eot /assets/re-com/fonts/Material-Design-Iconic-Font.svg /assets/re-com/fonts/Material-Design-Iconic-Font.ttf /assets/re-com/fonts/Material-Design-Iconic-Font.woff /assets/re-com/fonts/Material-Design-Iconic-Font.woff2 /assets/re-com/scripts/detect-element-resize.js /assets/css/app.css /shared.js /app.js".split(" "),
null)));self.addEventListener("install",function(a){return a.waitUntil(caches.open(sN.cacheNames.runtime).then(function(b){return b.addAll(wN)}))});self.addEventListener("message",function(a){a=null==a?null:a.data;return $APP.I.g(null==a?null:a.type,"SKIP_WAITING")?self.skipWaiting():null});tN.registerRoute(function(a){return $APP.I.g(a.request.destination,"image")},new vN.CacheFirst);tN.setDefaultHandler(new vN.StaleWhileRevalidate);uN.precacheAndRoute([{url:"/wiki-guides/",revision:"824432eb932a2e400d529ce078b063dc7d6ec2b831e9b02ef50e963d433c9d50"}]);
tN.registerRoute(new tN.NavigationRoute(uN.createHandlerBoundToURL("/wiki-guides/")));
}).call(this);